In [1]:
%pip uninstall -y pyarrow
%pip install pyarrow

Found existing installation: pyarrow 23.0.1Note: you may need to restart the kernel to use updated packages.

Uninstalling pyarrow-23.0.1:
  Successfully uninstalled pyarrow-23.0.1
Collecting pyarrowNote: you may need to restart the kernel to use updated packages.

  Using cached pyarrow-23.0.1-cp311-cp311-win_amd64.whl.metadata (3.1 kB)
Using cached pyarrow-23.0.1-cp311-cp311-win_amd64.whl (27.5 MB)
Installing collected packages: pyarrow
Successfully installed pyarrow-23.0.1

In [2]:
import pandas as pd
pd.__version__

'2.1.4'

In [3]:
%pip install psycopg2-binary sqlalchemy pandas

Requirement already satisfied: psycopg2-binary in c:\users\adam\anaconda3\lib\site-packages (2.9.11)
Requirement already satisfied: sqlalchemy in c:\users\adam\anaconda3\lib\site-packages (2.0.25)
Requirement already satisfied: pandas in c:\users\adam\anaconda3\lib\site-packages (2.1.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\adam\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\adam\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
Requirement already satisfied: numpy<2,>=1.23.2 in c:\users\adam\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\adam\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\adam\anaconda3\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\adam\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\adam\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
from sqlalchemy import create_engine
engine = create_engine(
    "postgresql+psycopg2://postgres:1620@localhost:5432/laz_test"
)
pd.read_sql("SELECT 1;", engine)

   ?column?
0         1

In [5]:
import pandas as pd

path = r"Test Verb Present tense.csv"   # adjust path if needed
raw = pd.read_csv(path, low_memory=False)

# keep only non-empty column names that aren't "Unnamed: ..."
df = raw.loc[:, ~raw.columns.str.startswith("Unnamed:")].copy()

df.columns
df.head()

,Laz Infinitive,Category,Laz 3rd Person Singular Present,Region,Laz 3rd Person Singular Present Alternative 1,Region Alternative 1,Laz 3rd Person Singular Present Alternative 2,Region Alternative 2,English Translation,Turkish Verb,verb_family_id
0,avara doskudu,TVM,avara doskudun,"PZ, AŞ, FA, HO",NaN,NaN,NaN,NaN,to be idle,avare kalmak,19
1,cebazgu,TVE,cobazgams,"PZ, AŞ",NaN,NaN,NaN,NaN,"to press, to step on something",basmak,139
2,cebgaru,TVE,cabgars,PZ,NaN,NaN,NaN,NaN,to lament over something,ağıt yakmak,108
3,ceçamu,TVE,ceçams,"PZ, AŞ",NaN,NaN,NaN,NaN,to hit something/someone,vurmak (bir şeye),98
4,ceç̌u,TVE,coç̌ams,"PZ, AŞ",NaN,NaN,NaN,NaN,to begin,başlamak,28

In [6]:
# clean + unique category codes
cats = (
    df[["Category"]]
    .dropna()
    .assign(code=lambda x: x["Category"].astype(str).str.strip())
    .drop_duplicates(subset=["code"])
    [["code"]]
)

# explicit mappings
english_map = {
    "IVD": "Dative verb",
    "TVM": "Nominative verb",
    "TVE": "Ergative verb",
}

turkish_map = {
    "IVD": "Yönelme fiili",
    "TVM": "Nominatif fiili",
    "TVE": "Ergatif fiili",
}

cats["english_name"] = cats["code"].map(english_map)
cats["turkish_name"] = cats["code"].map(turkish_map)

# final column order
cats = cats[["english_name", "turkish_name", "code"]]

cats

      english_name     turkish_name code
0  Nominative verb  Nominatif fiili  TVM
1    Ergative verb    Ergatif fiili  TVE
7      Dative verb    Yönelme fiili  IVD

In [7]:
pd.read_sql("""
SELECT column_name, is_nullable
FROM information_schema.columns
WHERE table_name = 'verb_category'
ORDER BY ordinal_position;
""", engine)

        column_name is_nullable
0  verb_category_id          NO
1              code          NO
2      english_name          NO
3      turkish_name          NO
4          laz_name         YES

In [8]:
cats.to_sql("verb_category", engine, if_exists="append", index=False) # double check, verb groups should be unique

3

In [9]:
pd.read_sql("SELECT * FROM verb_category ORDER BY verb_category_id;", engine)

   verb_category_id code     english_name     turkish_name laz_name
0                 1  TVM  Nominative verb  Nominatif fiili     None
1                 2  TVE    Ergative verb    Ergatif fiili     None
2                 3  IVD      Dative verb    Yönelme fiili     None

In [10]:
cat_map = pd.read_sql("SELECT verb_category_id, code FROM verb_category;", engine)
cat_map

   verb_category_id code
0                 1  TVM
1                 2  TVE
2                 3  IVD

In [11]:
# 1) build verbs from the CSV
verbs = (
    df[["Laz Infinitive", "Category"]]
    .dropna()
    .assign(
        infinitive=lambda x: x["Laz Infinitive"].astype(str).str.strip(),
        code=lambda x: x["Category"].astype(str).str.strip(),
    )
    .query("infinitive != ''")
    .drop_duplicates(subset=["infinitive", "code"])
    .merge(cat_map, on="code", how="left") # why is this necessary? Is it to get the verb category ID?
)

# 2) sanity check: any categories that didn't map?
bad = verbs[verbs["verb_category_id"].isna()][["infinitive", "code"]].drop_duplicates() 
bad

Empty DataFrame
Columns: [infinitive, code]
Index: []

In [12]:
dialects = pd.DataFrame([
    {"english_name": "Ardeşen", "turkish_name": "Ardeşen", "laz_name": "Art̆aşeni"},
    {"english_name": "Pazar", "turkish_name": "Pazar", "laz_name": "Atina"},
    {"english_name": "Fındıklı/Arhavi", "turkish_name": "Fındıklı/Arhavi", "laz_name": "Viǯe/Arkabi"},
    {"english_name": "Hopa", "turkish_name": "Hopa", "laz_name": "Xopa"},
])
dialects

      english_name     turkish_name     laz_name
0          Ardeşen          Ardeşen    Art̆aşeni
1            Pazar            Pazar        Atina
2  Fındıklı/Arhavi  Fındıklı/Arhavi  Viǯe/Arkabi
3             Hopa             Hopa         Xopa

In [13]:
existing = pd.read_sql("SELECT english_name FROM dialect;", engine)

dialects_new = dialects[~dialects["english_name"].isin(existing["english_name"])].copy() #
dialects_new

      english_name     turkish_name     laz_name
0          Ardeşen          Ardeşen    Art̆aşeni
1            Pazar            Pazar        Atina
2  Fındıklı/Arhavi  Fındıklı/Arhavi  Viǯe/Arkabi
3             Hopa             Hopa         Xopa

In [14]:
dialects_new.to_sql("dialect", engine, if_exists="append", index=False)

4

In [15]:
from sqlalchemy import text

with engine.begin() as conn:
    conn.execute(
        text("""
        UPDATE dialect
        SET laz_name = 'Art̆aşeni'
        WHERE english_name = 'Ardeşen';
        """)
    )

In [16]:
pd.read_sql(
    "SELECT dialect_id, english_name, turkish_name, laz_name FROM dialect ORDER BY dialect_id;",
    engine
)

   dialect_id     english_name     turkish_name     laz_name
0           1          Ardeşen          Ardeşen    Art̆aşeni
1           2            Pazar            Pazar        Atina
2           3  Fındıklı/Arhavi  Fındıklı/Arhavi  Viǯe/Arkabi
3           4             Hopa             Hopa         Xopa

In [17]:
DEFAULT_DIALECT_ID = int(pd.read_sql(
    "SELECT dialect_id FROM dialect WHERE english_name='Fındıklı/Arhavi';",
    engine
).iloc[0,0])
DEFAULT_DIALECT_ID

3

In [18]:
verbs = (
    df[["Laz Infinitive", "Category"]]
    .dropna()
    .assign(
        infinitive=lambda x: x["Laz Infinitive"].astype(str).str.strip(),
        code=lambda x: x["Category"].astype(str).str.strip(),
    )
    .query("infinitive != ''")
    .drop_duplicates(subset=["infinitive", "code"])
    .merge(cat_map, on="code", how="left")
)

# must be empty
verbs[verbs["verb_category_id"].isna()]

Empty DataFrame
Columns: [Laz Infinitive, Category, infinitive, code, verb_category_id]
Index: []

In [19]:
pd.read_sql("""
SELECT column_name, is_nullable
FROM information_schema.columns
WHERE table_name = 'verb'
ORDER BY ordinal_position;
""", engine)

               column_name is_nullable
0                  verb_id          NO
1           verb_family_id         YES
2       root_infinitive_id         YES
3               dialect_id          NO
4         verb_category_id          NO
5               infinitive          NO
6              present_3sg          NO
7          meaning_english          NO
8          meaning_turkish          NO
9          requires_marker          NO
10  has_optional_prefix_ko          NO
11  has_optional_prefix_do          NO

In [20]:
COL_INF = "Laz Infinitive"
COL_CAT = "Category"
COL_PRES3 = "Laz 3rd Person Singular Present"
COL_ENG = "English Translation"
COL_TR  = "Turkish Verb"

verbs = (
    df[[COL_INF, COL_CAT, COL_PRES3, COL_ENG, COL_TR]]
    .dropna(subset=[COL_INF, COL_CAT, COL_PRES3, COL_ENG, COL_TR])
    .assign(
        infinitive=lambda x: x[COL_INF].astype(str).str.strip(),
        code=lambda x: x[COL_CAT].astype(str).str.strip(),
        present_3sg=lambda x: x[COL_PRES3].astype(str).str.strip(),
        meaning_english=lambda x: x[COL_ENG].astype(str).str.strip(),
        meaning_turkish=lambda x: x[COL_TR].astype(str).str.strip(),
    )
    .query("infinitive != '' and present_3sg != '' and meaning_english != '' and meaning_turkish != ''")
    .drop_duplicates(subset=["infinitive", "code"]) # why drop these duplicates; not necessary at this stage (remove)
    .merge(cat_map, on="code", how="left")
)

# sanity: should be empty
missing = verbs[verbs["verb_category_id"].isna()]
missing

Empty DataFrame
Columns: [Laz Infinitive, Category, Laz 3rd Person Singular Present, English Translation, Turkish Verb, infinitive, code, present_3sg, meaning_english, meaning_turkish, verb_category_id]
Index: []

In [21]:
pd.read_sql("SELECT COUNT(*) AS n_verbs FROM verb;", engine)

   n_verbs
0        0

In [22]:
df.shape

(327, 11)

In [23]:
df[["Laz Infinitive","Category","Laz 3rd Person Singular Present","English Translation","Turkish Verb","Region"]].head(10)

,Laz Infinitive,Category,Laz 3rd Person Singular Present,English Translation,Turkish Verb,Region
0,avara doskudu,TVM,avara doskudun,to be idle,avare kalmak,"PZ, AŞ, FA, HO"
1,cebazgu,TVE,cobazgams,"to press, to step on something",basmak,"PZ, AŞ"
2,cebgaru,TVE,cabgars,to lament over something,ağıt yakmak,PZ
3,ceçamu,TVE,ceçams,to hit something/someone,vurmak (bir şeye),"PZ, AŞ"
4,ceç̌u,TVE,coç̌ams,to begin,başlamak,"PZ, AŞ"
5,cegapu,TVM,cagen,to get used to,alışmak,"PZ, AŞ"
6,ceginu,TVE,coginams,to get someone become familiar with something,alıştırmak,"PZ, AŞ"
7,cedginu,IVD,cadginen,to crave,aşermek,"PZ, AŞ"
8,celabalu,TVE,celabams,to hang,asmak,"PZ, AŞ"
9,cemp̌onu,TVE,comp̌onams,to vaccinate/fertilize,aşılamak,AŞ

In [24]:
COL_INF="Laz Infinitive"
COL_CAT="Category"
COL_PRES3="Laz 3rd Person Singular Present"
COL_ENG="English Translation"
COL_TR="Turkish Verb"
COL_REG="Region"

verbs = (
    df[[COL_INF, COL_CAT, COL_PRES3, COL_ENG, COL_TR, COL_REG]]
    .assign(
        infinitive=lambda x: x[COL_INF].astype(str).str.strip(),
        code=lambda x: x[COL_CAT].astype(str).str.strip(),
        present_3sg=lambda x: x[COL_PRES3].astype(str).str.strip(),
        meaning_english=lambda x: x[COL_ENG].astype(str).str.strip(),
        meaning_turkish=lambda x: x[COL_TR].astype(str).str.strip(),
        region=lambda x: x[COL_REG].astype(str).str.strip(),
    )
)

verbs.shape

(327, 12)

In [25]:
verbs[["infinitive","code","present_3sg","meaning_english","meaning_turkish","region"]].isna().sum()

infinitive         0
code               0
present_3sg        0
meaning_english    0
meaning_turkish    0
region             0
dtype: int64

In [26]:
usable = verbs.query("infinitive != '' and code != '' and present_3sg != ''")
usable.shape

(327, 12)

In [27]:
import pandas as pd

cat_map = pd.read_sql("SELECT verb_category_id, code FROM verb_category;", engine)

dialect_map = pd.read_sql("SELECT dialect_id, english_name FROM dialect;", engine)

# region code -> dialect english_name
region_to_english = {
    "AŞ": "Ardeşen",
    "PZ": "Pazar",
    "FA": "Fındıklı/Arhavi",
    "HO": "Hopa",
}

# turn dialect_map into english_name -> dialect_id
english_to_id = dict(zip(dialect_map["english_name"], dialect_map["dialect_id"]))

# final region code -> dialect_id
region_to_id = {k: english_to_id[v] for k, v in region_to_english.items()}
region_to_id

{'AŞ': 1, 'PZ': 2, 'FA': 3, 'HO': 4}

### Important terminology note
- **verb_family**: groups related lexical roots across dialects (e.g., *uqoun* ~ *uyonun* “to have”).
- **preverb variants** (e.g., *obaru*, *mebaru*, *ebaru*): should **not** be grouped via `verb_family_id`.
  If/when you add a CSV column like `preverb_family` (e.g., `obaru`), we can seed a `preverb_family` table and link verbs to it via `preverb_family_id`.

In [28]:
COL_INF="Laz Infinitive"
COL_CAT="Category"
COL_PRES3="Laz 3rd Person Singular Present"
COL_ENG="English Translation"
COL_TR="Turkish Verb"
COL_REG="Region"
COL_FAM ="verb_family_id"
# Optional column: preverb_family (groups preverb variants like obaru/mebaru/ebaru).
# If not present in the CSV, it will be treated as missing.
COL_PREFAM="preverb_family"
if COL_PREFAM not in df.columns:
    df[COL_PREFAM] = pd.NA

verbs = (
    df[[COL_INF, COL_CAT, COL_PRES3, COL_ENG, COL_TR, COL_REG, COL_FAM, COL_PREFAM]]
    .assign(
        infinitive=lambda x: x[COL_INF].astype(str).str.strip(),
        code=lambda x: x[COL_CAT].astype(str).str.strip(),
        present_3sg=lambda x: x[COL_PRES3].astype(str).str.strip(),
        meaning_english=lambda x: x[COL_ENG].astype(str).str.strip(),
        meaning_turkish=lambda x: x[COL_TR].astype(str).str.strip(),
        region=lambda x: x[COL_REG].astype(str).str.strip(),
        verb_family_id=lambda x: pd.to_numeric(x[COL_FAM], errors="coerce").astype("Int64"),
        preverb_family=lambda x: x[COL_PREFAM].astype(str).str.strip().replace({"": pd.NA, "nan": pd.NA}),
    )
    .query("infinitive != '' and code != '' and present_3sg != ''")
    .merge(cat_map, on="code", how="left")
)

# split "PZ, AŞ, FA" -> ["PZ","AŞ","FA"]
verbs = verbs.assign(
    region_code=lambda x: x["region"].str.split(",")
).explode("region_code")

verbs["region_code"] = verbs["region_code"].astype(str).str.strip()

# map to dialect_id
verbs["dialect_id"] = verbs["region_code"].map(region_to_id)

# sanity check: should be empty
bad = verbs[verbs["dialect_id"].isna()][["region","region_code"]].drop_duplicates()
bad

Empty DataFrame
Columns: [region, region_code]
Index: []

In [29]:
# --- Build verbs_to_insert to match your verb table ---

# If verbs_clean already exists from earlier cells, use it.
# Otherwise, create it from verbs (this makes the cell self-contained).
if "verbs_clean" in globals():
    base = verbs_clean.copy()
else:
    base = verbs.dropna(subset=["dialect_id", "verb_category_id"]).copy()

# ensure FK ints (verb_family_id can be NULL, so keep it as nullable Int64)
base["dialect_id"] = base["dialect_id"].astype(int)
base["verb_category_id"] = base["verb_category_id"].astype(int)

# Only do this if the column exists (prevents KeyError if you forgot the earlier step)
if "verb_family_id" in base.columns:
    base["verb_family_id"] = base["verb_family_id"].astype("Int64")
else:
    # If you hit this, it means the earlier "verbs =" cell didn't create verb_family_id
    raise KeyError("verb_family_id column is missing. Make sure your earlier step creates it from the CSV.")

verbs_to_insert = (
    base[[
        "verb_family_id",      # Cross-dialect lexical root group (uqoun ~ uyonun). Not preverb mapping.
        "verb_category_id",
        "dialect_id",
        "infinitive",
        "present_3sg",
        "meaning_english",
        "meaning_turkish",
    ]]
    .drop_duplicates()
    .copy()
)

# required booleans (set defaults for now; you can refine later)
verbs_to_insert["requires_marker"] = False


# IMPORTANT: de-dupe on your conflict target (dialect_id, infinitive)
verbs_to_insert = verbs_to_insert.drop_duplicates(subset=["dialect_id", "infinitive"])

verbs_to_insert.head()

,verb_family_id,verb_category_id,dialect_id,infinitive,present_3sg,meaning_english,meaning_turkish,requires_marker
0,19,1,2,avara doskudu,avara doskudun,to be idle,avare kalmak,False
0,19,1,1,avara doskudu,avara doskudun,to be idle,avare kalmak,False
0,19,1,3,avara doskudu,avara doskudun,to be idle,avare kalmak,False
0,19,1,4,avara doskudu,avara doskudun,to be idle,avare kalmak,False
1,139,2,2,cebazgu,cobazgams,"to press, to step on something",basmak,False

In [30]:
print(type(verbs_to_insert))
print(verbs_to_insert.shape)
display(verbs_to_insert.head())

<class 'pandas.core.frame.DataFrame'>
(653, 8)

,verb_family_id,verb_category_id,dialect_id,infinitive,present_3sg,meaning_english,meaning_turkish,requires_marker
0,19,1,2,avara doskudu,avara doskudun,to be idle,avare kalmak,False
0,19,1,1,avara doskudu,avara doskudun,to be idle,avare kalmak,False
0,19,1,3,avara doskudu,avara doskudun,to be idle,avare kalmak,False
0,19,1,4,avara doskudu,avara doskudun,to be idle,avare kalmak,False
1,139,2,2,cebazgu,cobazgams,"to press, to step on something",basmak,False

In [31]:
print(verbs[[COL_INF, "region"]].head(20))
print(verbs["region"].value_counts(dropna=False).head(20))
print("blank region rows:", (verbs["region"] == "").sum())
print("'nan' region rows:", (verbs["region"] == "nan").sum())

  Laz Infinitive          region
0  avara doskudu  PZ, AŞ, FA, HO
0  avara doskudu  PZ, AŞ, FA, HO
0  avara doskudu  PZ, AŞ, FA, HO
0  avara doskudu  PZ, AŞ, FA, HO
1        cebazgu          PZ, AŞ
1        cebazgu          PZ, AŞ
2        cebgaru              PZ
3         ceçamu          PZ, AŞ
3         ceçamu          PZ, AŞ
4          ceç̌u          PZ, AŞ
4          ceç̌u          PZ, AŞ
5         cegapu          PZ, AŞ
5         cegapu          PZ, AŞ
6         ceginu          PZ, AŞ
6         ceginu          PZ, AŞ
7        cedginu          PZ, AŞ
7        cedginu          PZ, AŞ
8       celabalu          PZ, AŞ
8       celabalu          PZ, AŞ
9       cemp̌onu              AŞ
region
PZ, AŞ, FA        213
PZ, AŞ, FA, HO    140
HO                 72
PZ, AŞ             70
FA, HO             44
FA                 36
FA, PZ, AŞ         30
FA, AŞ, PZ         27
AŞ, PZ             18
AŞ                  9
PZ                  8
AŞ, FA              8
PZ, AŞ, HO          6
AŞ, PZ, HO, FA      4
PZ, FA, AŞ          3
AŞ, PZ, FA          3
FA, PZ              2
PZ, HO              2
Name: count, dtype: int64
blank region rows: 0
'nan' region rows: 0

In [32]:
# --- Ensure verb_family rows exist (needed before inserting verbs with verb_family_id FK) ---
# Because schema.sql defines verb_family_id as GENERATED BY DEFAULT AS IDENTITY,
# we *can* insert explicit verb_family_id values from the CSV when recreating the DB.

import pandas as pd
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import insert

# 1) Collect unique, non-null verb_family_id values from the CSV-derived dataframe
family_ids = (
    verbs_to_insert["verb_family_id"]
    .dropna()
    .astype(int)
    .drop_duplicates()
    .sort_values()
)

verb_family_seed = pd.DataFrame({
    "verb_family_id": family_ids,
    "family_code": [None] * len(family_ids), 
})

# 2) Pull existing IDs from DB so we only insert missing ones
existing_ids = pd.read_sql("SELECT verb_family_id FROM verb_family;", engine)["verb_family_id"].tolist()
existing_ids = set(int(x) for x in existing_ids)

to_insert = verb_family_seed[~verb_family_seed["verb_family_id"].isin(existing_ids)].copy()
print(f"verb_family already in DB: {len(existing_ids)}")
print(f"verb_family new to insert: {len(to_insert)}")

# 3) Insert missing rows (ON CONFLICT DO NOTHING)
meta = sa.MetaData()
verb_family_tbl = sa.Table("verb_family", meta, autoload_with=engine)

if not to_insert.empty:
    with engine.begin() as conn:
        rows = to_insert.to_dict(orient="records")
        stmt = insert(verb_family_tbl).values(rows).on_conflict_do_nothing(
            index_elements=["verb_family_id"]
        )
        conn.execute(stmt)

verb_family already in DB: 0
verb_family new to insert: 205

In [33]:
print(verbs[[COL_INF, "region"]].head(20))
print(verbs["region"].value_counts(dropna=False).head(20))
print("blank region rows:", (verbs["region"] == "").sum())
print("'nan' region rows:", (verbs["region"] == "nan").sum())

  Laz Infinitive          region
0  avara doskudu  PZ, AŞ, FA, HO
0  avara doskudu  PZ, AŞ, FA, HO
0  avara doskudu  PZ, AŞ, FA, HO
0  avara doskudu  PZ, AŞ, FA, HO
1        cebazgu          PZ, AŞ
1        cebazgu          PZ, AŞ
2        cebgaru              PZ
3         ceçamu          PZ, AŞ
3         ceçamu          PZ, AŞ
4          ceç̌u          PZ, AŞ
4          ceç̌u          PZ, AŞ
5         cegapu          PZ, AŞ
5         cegapu          PZ, AŞ
6         ceginu          PZ, AŞ
6         ceginu          PZ, AŞ
7        cedginu          PZ, AŞ
7        cedginu          PZ, AŞ
8       celabalu          PZ, AŞ
8       celabalu          PZ, AŞ
9       cemp̌onu              AŞ
region
PZ, AŞ, FA        213
PZ, AŞ, FA, HO    140
HO                 72
PZ, AŞ             70
FA, HO             44
FA                 36
FA, PZ, AŞ         30
FA, AŞ, PZ         27
AŞ, PZ             18
AŞ                  9
PZ                  8
AŞ, FA              8
PZ, AŞ, HO          6
AŞ, PZ, HO, FA      4
PZ, FA, AŞ          3
AŞ, PZ, FA          3
FA, PZ              2
PZ, HO              2
Name: count, dtype: int64
blank region rows: 0
'nan' region rows: 0

In [34]:
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import insert

# ---- 1) Reflect the verb table from the DB ----
meta = sa.MetaData()
verb_tbl = sa.Table("verb", meta, autoload_with=engine)

def insert_ignore_duplicates(table, conn, keys, data_iter):
    """
    Pandas to_sql 'method' callable:
    UPSERT rows into verb. On conflict (dialect_id, infinitive), UPDATE columns
    so previously-inserted rows get their verb_family_id filled in.
    """
    rows = [dict(zip(keys, row)) for row in data_iter]
    if not rows:
        return 0

    stmt = insert(verb_tbl).values(rows)

    # Only update columns that exist in the DB table AND are present in the incoming rows
    incoming_cols = set(rows[0].keys())
    db_cols = set(verb_tbl.columns.keys())

    desired_updates = {
        "verb_family_id",
        "verb_category_id",
        "present_3sg",
        "meaning_english",
        "meaning_turkish",
        "requires_marker",
        "has_optional_prefix_ko",
        "has_optional_prefix_do",    }

    update_cols = sorted(list(desired_updates & incoming_cols & db_cols))

    if not update_cols:
        stmt = stmt.on_conflict_do_nothing(index_elements=["dialect_id", "infinitive"])
    else:
        stmt = stmt.on_conflict_do_update(
            index_elements=["dialect_id", "infinitive"],
            set_={c: getattr(stmt.excluded, c) for c in update_cols},
        )

    result = conn.execute(stmt)
    return result.rowcount


# ---- 2) Ensure verbs_to_insert exists (build it if missing) ----
if "verbs_to_insert" not in globals():
    if "verbs_clean" not in globals():
        raise NameError("verbs_clean is not defined yet. Run the cell that creates verbs_clean before inserting.")
    verbs_to_insert = (
        verbs_clean[[
            "verb_family_id",
            "verb_category_id",
            "dialect_id",
            "infinitive",
            "present_3sg",
            "meaning_english",
            "meaning_turkish",
        ]]
        .drop_duplicates()
        .copy()
    )

# ---- 3) Add defaults for DB columns that aren't in the CSV ----
# (we only add them if they exist in the DB table)
db_cols = [c.name for c in verb_tbl.columns]

for col in ["requires_marker",
            "has_optional_prefix_ko", "has_optional_prefix_do"]:
    if col in db_cols and col not in verbs_to_insert.columns:
        verbs_to_insert[col] = False

# ---- 4) Drop extra columns not present in the DB ----
extra = [c for c in verbs_to_insert.columns if c not in db_cols]
if extra:
    print("Dropping columns not in DB verb table:", extra)
    verbs_to_insert = verbs_to_insert.drop(columns=extra)

# ---- 5) Deduplicate on the conflict target and insert ----
verbs_to_insert = verbs_to_insert.drop_duplicates(subset=["dialect_id", "infinitive"]).copy()

with engine.begin() as conn:
    verbs_to_insert.to_sql(
        "verb",
        con=conn,
        if_exists="append",
        index=False,
        method=insert_ignore_duplicates,
        chunksize=1000,
    )

pd.read_sql("SELECT COUNT(*) AS n_verbs FROM verb;", engine)

   n_verbs
0      653

In [35]:
print(verbs[[COL_INF, "region"]].head(20))
print(verbs["region"].value_counts(dropna=False).head(20))
print("blank region rows:", (verbs["region"] == "").sum())
print("'nan' region rows:", (verbs["region"] == "nan").sum())

  Laz Infinitive          region
0  avara doskudu  PZ, AŞ, FA, HO
0  avara doskudu  PZ, AŞ, FA, HO
0  avara doskudu  PZ, AŞ, FA, HO
0  avara doskudu  PZ, AŞ, FA, HO
1        cebazgu          PZ, AŞ
1        cebazgu          PZ, AŞ
2        cebgaru              PZ
3         ceçamu          PZ, AŞ
3         ceçamu          PZ, AŞ
4          ceç̌u          PZ, AŞ
4          ceç̌u          PZ, AŞ
5         cegapu          PZ, AŞ
5         cegapu          PZ, AŞ
6         ceginu          PZ, AŞ
6         ceginu          PZ, AŞ
7        cedginu          PZ, AŞ
7        cedginu          PZ, AŞ
8       celabalu          PZ, AŞ
8       celabalu          PZ, AŞ
9       cemp̌onu              AŞ
region
PZ, AŞ, FA        213
PZ, AŞ, FA, HO    140
HO                 72
PZ, AŞ             70
FA, HO             44
FA                 36
FA, PZ, AŞ         30
FA, AŞ, PZ         27
AŞ, PZ             18
AŞ                  9
PZ                  8
AŞ, FA              8
PZ, AŞ, HO          6
AŞ, PZ, HO, FA      4
PZ, FA, AŞ          3
AŞ, PZ, FA          3
FA, PZ              2
PZ, HO              2
Name: count, dtype: int64
blank region rows: 0
'nan' region rows: 0

In [36]:
# --- Insert into verb, skipping duplicates safely ---
# Goal: align DataFrame columns to the actual DB table columns before to_sql()

# 1) Pull the true DB schema for the verb table
verb_cols = pd.read_sql("""
SELECT column_name
FROM information_schema.columns
WHERE table_schema = 'public' AND table_name = 'verb'
ORDER BY ordinal_position;
""", engine)["column_name"].tolist()

df = verbs_to_insert.copy()

# 2) Add defaults for columns that exist in SQL but not in the CSV/DataFrame
# (This handles optional-column defaults automatically.)
defaults_false = [
    "requires_marker",
    "has_optional_prefix_ko",
    "has_optional_prefix_do",]

for col in defaults_false:
    if col in verb_cols and col not in df.columns:
        df[col] = False

# If your table has other nullable columns you want to set explicitly, do it here.
# Example:
# if "notes" in verb_cols and "notes" not in df.columns:
#     df["notes"] = None

# 3) Drop any DataFrame columns that are NOT in the SQL table
extra = [c for c in df.columns if c not in verb_cols]
if extra:
    print("Dropping columns not in DB table:", extra)
    df = df.drop(columns=extra)

# 4) Reorder columns to match the table (optional but keeps things tidy)
df = df[[c for c in verb_cols if c in df.columns]]

# 5) Insert
with engine.begin() as conn:
    df.to_sql(
        "verb",
        con=conn,
        if_exists="append",
        index=False,
        method=insert_ignore_duplicates,
        chunksize=1000,
    )

pd.read_sql("SELECT COUNT(*) AS n_verbs FROM verb;", engine)

   n_verbs
0      653

In [37]:
# --- sanity sample: did inserts land the way we expect? ---
pd.read_sql("""
SELECT dialect_id, infinitive, present_3sg, verb_category_id
FROM verb
ORDER BY verb_id DESC
LIMIT 20;
""", engine)

    dialect_id     infinitive      present_3sg  verb_category_id
0            1        cexvamu        cuxvamams                 2
1            2        cexvamu        cuxvamams                 2
2            3        gexvamu       gyuxvamams                 2
3            4        zop̌ini          zop̌ons                 2
4            3        zop̌ini          zop̌ons                 2
5            1   yoxo cedvalu      yoxo codums                 2
6            2   yoxo cedvalu      yoxo codums                 2
7            4        yeç̌opu        yeç̌opups                 2
8            4  xe oǩotvaʒinu  xe oǩotvaʒinaps                 2
9            2   xe oǩoç̌apxu   xe oǩoç̌apxams                 2
10           1   xe oǩoç̌apxu   xe oǩoç̌apxams                 2
11           3   xe oǩoç̌apxu   xe oǩoç̌apxams                 2
12           3         uyonun           uyonun                 3
13           1         uyonun           uyonun                 3
14           2         uyonun           uyonun                 3
15           4          uqoun            uqoun                 3
16           4           unon             unon                 3
17           3           unon             unon                 3
18           4           uğun             uğun                 3
19           3           uğun             uğun                 3

In [38]:
# --- Post-import checks ---

# How many rows did we insert?
pd.read_sql("SELECT COUNT(*) AS n_verbs FROM verb;", engine)

   n_verbs
0      653

In [39]:
# Check for duplicates on your natural key (dialect_id, infinitive)
pd.read_sql("""
SELECT dialect_id, infinitive, COUNT(*) AS n
FROM verb
GROUP BY dialect_id, infinitive
HAVING COUNT(*) > 1
ORDER BY n DESC, dialect_id, infinitive
LIMIT 50;
""", engine)

Empty DataFrame
Columns: [dialect_id, infinitive, n]
Index: []

In [40]:
# Quick spot-check: sample rows
pd.read_sql("""
SELECT v.verb_id,
       v.verb_family_id,
       d.english_name AS dialect,
       vc.english_name AS category,
       v.infinitive,
       v.present_3sg,
       v.meaning_english,
       v.meaning_turkish
FROM verb v
JOIN dialect d ON d.dialect_id = v.dialect_id
JOIN verb_category vc ON vc.verb_category_id = v.verb_category_id
ORDER BY v.verb_id DESC
LIMIT 25;
""", engine)

,verb_id,verb_family_id,dialect,category,infinitive,present_3sg,meaning_english,meaning_turkish
0,653,210,Ardeşen,Ergative verb,cexvamu,cuxvamams,to celebrate,kutlamak
1,652,210,Pazar,Ergative verb,cexvamu,cuxvamams,to celebrate,kutlamak
2,651,210,Fındıklı/Arhavi,Ergative verb,gexvamu,gyuxvamams,to celebrate,kutlamak
3,650,38,Hopa,Ergative verb,zop̌ini,zop̌ons,"to mention, to talk about",bahsetmek
4,649,38,Fındıklı/Arhavi,Ergative verb,zop̌ini,zop̌ons,"to mention, to talk about",bahsetmek
5,648,38,Ardeşen,Ergative verb,yoxo cedvalu,yoxo codums,to name something/someone,adlandırmak
6,647,38,Pazar,Ergative verb,yoxo cedvalu,yoxo codums,to name something/someone,adlandırmak
7,646,125,Hopa,Ergative verb,yeç̌opu,yeç̌opups,to buy,almak
8,645,130,Hopa,Ergative verb,xe oǩotvaʒinu,xe oǩotvaʒinaps,to applaud,alkışlamak
9,644,34,Pazar,Ergative verb,xe oǩoç̌apxu,xe oǩoç̌apxams,to applaud,alkışlamak
10,643,34,Ardeşen,Ergative verb,xe oǩoç̌apxu,xe oǩoç̌apxams,to applaud,alkışlamak
11,642,34,Fındıklı/Arhavi,Ergative verb,xe oǩoç̌apxu,xe oǩoç̌apxams,to applaud,alkışlamak
12,641,6,Fındıklı/Arhavi,Dative verb,uyonun,uyonun,to have,var (canlı)
13,640,6,Ardeşen,Dative verb,uyonun,uyonun,to have,var (canlı)
14,639,6,Pazar,Dative verb,uyonun,uyonun,to have,var (canlı)
15,638,6,Hopa,Dative verb,uqoun,uqoun,to have,var (canlı)
16,637,95,Hopa,Dative verb,unon,unon,to want,istemek
17,636,95,Fındıklı/Arhavi,Dative verb,unon,unon,to want,istemek
18,635,95,Hopa,Dative verb,uğun,uğun,to have,var (cansız)
19,634,95,Fındıklı/Arhavi,Dative verb,uğun,uğun,to have,var (cansız)
20,633,95,Ardeşen,Dative verb,uğun,uğun,to have,var (cansız)
21,632,95,Pazar,Dative verb,uğun,uğun,to have,var (cansız)
22,631,203,Hopa,Nominative verb,ren,ren,to be,olmak
23,630,203,Fındıklı/Arhavi,Nominative verb,ren,ren,to be,olmak
24,629,95,Fındıklı/Arhavi,Ergative verb,oʒxunu,ʒxunums,"to distinguish, to differentiate",ayrım yapmak

In [41]:
# Ensure all dialect_id/category_id mappings existed in the CSV
# (These should be empty if your earlier mapping diagnostics passed)
print("Unmapped dialect_id rows:", verbs[verbs["dialect_id"].isna()].shape[0])
print("Unmapped verb_category_id rows:", verbs[verbs["verb_category_id"].isna()].shape[0])

Unmapped dialect_id rows: 0
Unmapped verb_category_id rows: 0

In [42]:
import pandas as pd

preverbs = [
    "ce","cela","ceşǩa","dolo","e","eşǩa",
    "me","mo", "gela", "ge",
    "meo","moo","mola","gola","moǩo",
    "ama","gama","eo","meşǩa","go","goo","koǯo","eǯa","eǩa",
    "oǩo","ǩoşǩa", "ela",
    "oxo","do", "ye",
]

preverb_df = pd.DataFrame({"spelling": preverbs}).drop_duplicates().sort_values("spelling")

# Optional: normalize whitespace
preverb_df["spelling"] = preverb_df["spelling"].str.strip()

preverb_df

   spelling
15      ama
0        ce
1      cela
2     ceşǩa
28       do
3      dolo
4         e
26      ela
17       eo
5      eşǩa
23      eǩa
22      eǯa
16     gama
9        ge
8      gela
19       go
13     gola
20      goo
21     koǯo
6        me
10      meo
18    meşǩa
7        mo
12     mola
11      moo
14     moǩo
27      oxo
24      oǩo
29       ye
25    ǩoşǩa

In [43]:
import pandas as pd

# --- Make sure we have a "spelling" column no matter what the source column is called ---

preverb_df_db = preverb_df.copy()

if "spelling" not in preverb_df_db.columns:
    if "code" in preverb_df_db.columns:
        preverb_df_db = preverb_df_db.rename(columns={"code": "spelling"})
    else:
        raise ValueError(f"Expected a 'code' or 'spelling' column, found: {list(preverb_df_db.columns)}")

# keep only the columns that exist in the SQL table
preverb_df_db = preverb_df_db[["spelling"]].copy()

# optional columns (table has them, so we can set them)
preverb_df_db["preverb_group"] = None
preverb_df_db["notes"] = None

# clean + normalize
preverb_df_db["spelling"] = (
    preverb_df_db["spelling"]
    .astype(str)
    .str.strip()
)

# drop blanks just in case
preverb_df_db = preverb_df_db[preverb_df_db["spelling"] != ""]

# dedupe + stable order
preverb_df_db = preverb_df_db.drop_duplicates(subset=["spelling"]).sort_values("spelling").reset_index(drop=True)

# 1) pull existing spellings from DB
existing = pd.read_sql("SELECT spelling FROM preverb;", engine)
existing_set = set(existing["spelling"].astype(str).str.strip())

# 2) keep only new spellings
to_insert = preverb_df_db[~preverb_df_db["spelling"].isin(existing_set)].copy()

print(f"Already in DB: {len(existing_set)}")
print(f"New to insert: {len(to_insert)}")

# 3) insert only new ones
if not to_insert.empty:
    with engine.begin() as conn:
        to_insert.to_sql(
            "preverb",
            con=conn,
            if_exists="append",
            index=False,
            chunksize=1000,
        )

pd.read_sql("""
SELECT preverb_id, spelling, preverb_group, notes
FROM preverb
ORDER BY spelling;
""", engine)

Already in DB: 0
New to insert: 30

    preverb_id spelling preverb_group notes
0            1      ama          None  None
1            2       ce          None  None
2            3     cela          None  None
3            4    ceşǩa          None  None
4            5       do          None  None
5            6     dolo          None  None
6            7        e          None  None
7           11      eǩa          None  None
8            8      ela          None  None
9            9       eo          None  None
10          10     eşǩa          None  None
11          12      eǯa          None  None
12          13     gama          None  None
13          14       ge          None  None
14          15     gela          None  None
15          16       go          None  None
16          17     gola          None  None
17          18      goo          None  None
18          30    ǩoşǩa          None  None
19          19     koǯo          None  None
20          20       me          None  None
21          21      meo          None  None
22          22    meşǩa          None  None
23          23       mo          None  None
24          26     moǩo          None  None
25          24     mola          None  None
26          25      moo          None  None
27          28      oǩo          None  None
28          27      oxo          None  None
29          29       ye          None  None

In [44]:
pd.read_sql("SELECT preverb_id, spelling, preverb_group, notes FROM preverb ORDER BY spelling;", engine)

    preverb_id spelling preverb_group notes
0            1      ama          None  None
1            2       ce          None  None
2            3     cela          None  None
3            4    ceşǩa          None  None
4            5       do          None  None
5            6     dolo          None  None
6            7        e          None  None
7           11      eǩa          None  None
8            8      ela          None  None
9            9       eo          None  None
10          10     eşǩa          None  None
11          12      eǯa          None  None
12          13     gama          None  None
13          14       ge          None  None
14          15     gela          None  None
15          16       go          None  None
16          17     gola          None  None
17          18      goo          None  None
18          30    ǩoşǩa          None  None
19          19     koǯo          None  None
20          20       me          None  None
21          21      meo          None  None
22          22    meşǩa          None  None
23          23       mo          None  None
24          26     moǩo          None  None
25          24     mola          None  None
26          25      moo          None  None
27          28      oǩo          None  None
28          27      oxo          None  None
29          29       ye          None  None

In [45]:
print("rows in verbs_to_insert:", len(verbs_to_insert))
print("nonnull verb_family_id in df:", verbs_to_insert["verb_family_id"].notna().sum())

rows in verbs_to_insert: 653
nonnull verb_family_id in df: 653

In [46]:
# double checking to see which df to use for conjugation csv:
import pandas as pd

items = list(globals().items())
dfs = [(name, obj) for name, obj in items if isinstance(obj, pd.DataFrame)]

def looks_relevant(df: pd.DataFrame) -> bool:
    cols = " ".join(map(str, df.columns)).lower()
    return ("infinit" in cols) or ("laz" in cols) or ("verb" in cols) or ("region" in cols)

for name, df in dfs:
    if looks_relevant(df):
        print("\n" + "="*80)
        print(name)
        print("Shape:", df.shape)
        print("Columns:", list(df.columns))

        display(df.head(3))

================================================================================
_
Shape: (30, 4)
Columns: ['preverb_id', 'spelling', 'preverb_group', 'notes']

   preverb_id spelling preverb_group notes
0           1      ama          None  None
1           2       ce          None  None
2           3     cela          None  None

================================================================================
__
Shape: (30, 4)
Columns: ['preverb_id', 'spelling', 'preverb_group', 'notes']

   preverb_id spelling preverb_group notes
0           1      ama          None  None
1           2       ce          None  None
2           3     cela          None  None

================================================================================
raw
Shape: (327, 11)
Columns: ['Laz Infinitive', 'Category', 'Laz 3rd Person Singular Present', 'Region', 'Laz 3rd Person Singular Present Alternative 1', 'Region Alternative 1', 'Laz 3rd Person Singular Present Alternative 2', 'Region Alternative 2', 'English Translation', 'Turkish Verb', 'verb_family_id']

,Laz Infinitive,Category,Laz 3rd Person Singular Present,Region,Laz 3rd Person Singular Present Alternative 1,Region Alternative 1,Laz 3rd Person Singular Present Alternative 2,Region Alternative 2,English Translation,Turkish Verb,verb_family_id
0,avara doskudu,TVM,avara doskudun,"PZ, AŞ, FA, HO",NaN,NaN,NaN,NaN,to be idle,avare kalmak,19
1,cebazgu,TVE,cobazgams,"PZ, AŞ",NaN,NaN,NaN,NaN,"to press, to step on something",basmak,139
2,cebgaru,TVE,cabgars,PZ,NaN,NaN,NaN,NaN,to lament over something,ağıt yakmak,108

================================================================================
df
Shape: (653, 10)
Columns: ['verb_family_id', 'dialect_id', 'verb_category_id', 'infinitive', 'present_3sg', 'meaning_english', 'meaning_turkish', 'requires_marker', 'has_optional_prefix_ko', 'has_optional_prefix_do']

,verb_family_id,dialect_id,verb_category_id,infinitive,present_3sg,meaning_english,meaning_turkish,requires_marker,has_optional_prefix_ko,has_optional_prefix_do
0,19,2,1,avara doskudu,avara doskudun,to be idle,avare kalmak,False,False,False
0,19,1,1,avara doskudu,avara doskudun,to be idle,avare kalmak,False,False,False
0,19,3,1,avara doskudu,avara doskudun,to be idle,avare kalmak,False,False,False

================================================================================
_5
Shape: (5, 11)
Columns: ['Laz Infinitive', 'Category', 'Laz 3rd Person Singular Present', 'Region', 'Laz 3rd Person Singular Present Alternative 1', 'Region Alternative 1', 'Laz 3rd Person Singular Present Alternative 2', 'Region Alternative 2', 'English Translation', 'Turkish Verb', 'verb_family_id']

,Laz Infinitive,Category,Laz 3rd Person Singular Present,Region,Laz 3rd Person Singular Present Alternative 1,Region Alternative 1,Laz 3rd Person Singular Present Alternative 2,Region Alternative 2,English Translation,Turkish Verb,verb_family_id
0,avara doskudu,TVM,avara doskudun,"PZ, AŞ, FA, HO",NaN,NaN,NaN,NaN,to be idle,avare kalmak,19
1,cebazgu,TVE,cobazgams,"PZ, AŞ",NaN,NaN,NaN,NaN,"to press, to step on something",basmak,139
2,cebgaru,TVE,cabgars,PZ,NaN,NaN,NaN,NaN,to lament over something,ağıt yakmak,108

================================================================================
_9
Shape: (3, 5)
Columns: ['verb_category_id', 'code', 'english_name', 'turkish_name', 'laz_name']

   verb_category_id code     english_name     turkish_name laz_name
0                 1  TVM  Nominative verb  Nominatif fiili     None
1                 2  TVE    Ergative verb    Ergatif fiili     None
2                 3  IVD      Dative verb    Yönelme fiili     None

================================================================================
cat_map
Shape: (3, 2)
Columns: ['verb_category_id', 'code']

   verb_category_id code
0                 1  TVM
1                 2  TVE
2                 3  IVD

================================================================================
_10
Shape: (3, 2)
Columns: ['verb_category_id', 'code']

   verb_category_id code
0                 1  TVM
1                 2  TVE
2                 3  IVD

================================================================================
verbs
Shape: (695, 17)
Columns: ['Laz Infinitive', 'Category', 'Laz 3rd Person Singular Present', 'English Translation', 'Turkish Verb', 'Region', 'verb_family_id', 'preverb_family', 'infinitive', 'code', 'present_3sg', 'meaning_english', 'meaning_turkish', 'region', 'verb_category_id', 'region_code', 'dialect_id']

,Laz Infinitive,Category,Laz 3rd Person Singular Present,English Translation,Turkish Verb,Region,verb_family_id,preverb_family,infinitive,code,present_3sg,meaning_english,meaning_turkish,region,verb_category_id,region_code,dialect_id
0,avara doskudu,TVM,avara doskudun,to be idle,avare kalmak,"PZ, AŞ, FA, HO",19,<NA>,avara doskudu,TVM,avara doskudun,to be idle,avare kalmak,"PZ, AŞ, FA, HO",1,PZ,2
0,avara doskudu,TVM,avara doskudun,to be idle,avare kalmak,"PZ, AŞ, FA, HO",19,<NA>,avara doskudu,TVM,avara doskudun,to be idle,avare kalmak,"PZ, AŞ, FA, HO",1,AŞ,1
0,avara doskudu,TVM,avara doskudun,to be idle,avare kalmak,"PZ, AŞ, FA, HO",19,<NA>,avara doskudu,TVM,avara doskudun,to be idle,avare kalmak,"PZ, AŞ, FA, HO",1,FA,3

================================================================================
bad
Shape: (0, 2)
Columns: ['region', 'region_code']

Empty DataFrame
Columns: [region, region_code]
Index: []

================================================================================
_11
Shape: (0, 2)
Columns: ['infinitive', 'code']

Empty DataFrame
Columns: [infinitive, code]
Index: []

================================================================================
dialects
Shape: (4, 3)
Columns: ['english_name', 'turkish_name', 'laz_name']

      english_name     turkish_name     laz_name
0          Ardeşen          Ardeşen    Art̆aşeni
1            Pazar            Pazar        Atina
2  Fındıklı/Arhavi  Fındıklı/Arhavi  Viǯe/Arkabi

================================================================================
_12
Shape: (4, 3)
Columns: ['english_name', 'turkish_name', 'laz_name']

      english_name     turkish_name     laz_name
0          Ardeşen          Ardeşen    Art̆aşeni
1            Pazar            Pazar        Atina
2  Fındıklı/Arhavi  Fındıklı/Arhavi  Viǯe/Arkabi

================================================================================
dialects_new
Shape: (4, 3)
Columns: ['english_name', 'turkish_name', 'laz_name']

      english_name     turkish_name     laz_name
0          Ardeşen          Ardeşen    Art̆aşeni
1            Pazar            Pazar        Atina
2  Fındıklı/Arhavi  Fındıklı/Arhavi  Viǯe/Arkabi

================================================================================
_13
Shape: (4, 3)
Columns: ['english_name', 'turkish_name', 'laz_name']

      english_name     turkish_name     laz_name
0          Ardeşen          Ardeşen    Art̆aşeni
1            Pazar            Pazar        Atina
2  Fındıklı/Arhavi  Fındıklı/Arhavi  Viǯe/Arkabi

================================================================================
_16
Shape: (4, 4)
Columns: ['dialect_id', 'english_name', 'turkish_name', 'laz_name']

   dialect_id     english_name     turkish_name     laz_name
0           1          Ardeşen          Ardeşen    Art̆aşeni
1           2            Pazar            Pazar        Atina
2           3  Fındıklı/Arhavi  Fındıklı/Arhavi  Viǯe/Arkabi

================================================================================
_18
Shape: (0, 5)
Columns: ['Laz Infinitive', 'Category', 'infinitive', 'code', 'verb_category_id']

Empty DataFrame
Columns: [Laz Infinitive, Category, infinitive, code, verb_category_id]
Index: []

================================================================================
missing
Shape: (0, 11)
Columns: ['Laz Infinitive', 'Category', 'Laz 3rd Person Singular Present', 'English Translation', 'Turkish Verb', 'infinitive', 'code', 'present_3sg', 'meaning_english', 'meaning_turkish', 'verb_category_id']

Empty DataFrame
Columns: [Laz Infinitive, Category, Laz 3rd Person Singular Present, English Translation, Turkish Verb, infinitive, code, present_3sg, meaning_english, meaning_turkish, verb_category_id]
Index: []

================================================================================
_20
Shape: (0, 11)
Columns: ['Laz Infinitive', 'Category', 'Laz 3rd Person Singular Present', 'English Translation', 'Turkish Verb', 'infinitive', 'code', 'present_3sg', 'meaning_english', 'meaning_turkish', 'verb_category_id']

Empty DataFrame
Columns: [Laz Infinitive, Category, Laz 3rd Person Singular Present, English Translation, Turkish Verb, infinitive, code, present_3sg, meaning_english, meaning_turkish, verb_category_id]
Index: []

================================================================================
_21
Shape: (1, 1)
Columns: ['n_verbs']

   n_verbs
0        0

================================================================================
_23
Shape: (10, 6)
Columns: ['Laz Infinitive', 'Category', 'Laz 3rd Person Singular Present', 'English Translation', 'Turkish Verb', 'Region']

,Laz Infinitive,Category,Laz 3rd Person Singular Present,English Translation,Turkish Verb,Region
0,avara doskudu,TVM,avara doskudun,to be idle,avare kalmak,"PZ, AŞ, FA, HO"
1,cebazgu,TVE,cobazgams,"to press, to step on something",basmak,"PZ, AŞ"
2,cebgaru,TVE,cabgars,to lament over something,ağıt yakmak,PZ

================================================================================
usable
Shape: (327, 12)
Columns: ['Laz Infinitive', 'Category', 'Laz 3rd Person Singular Present', 'English Translation', 'Turkish Verb', 'Region', 'infinitive', 'code', 'present_3sg', 'meaning_english', 'meaning_turkish', 'region']

,Laz Infinitive,Category,Laz 3rd Person Singular Present,English Translation,Turkish Verb,Region,infinitive,code,present_3sg,meaning_english,meaning_turkish,region
0,avara doskudu,TVM,avara doskudun,to be idle,avare kalmak,"PZ, AŞ, FA, HO",avara doskudu,TVM,avara doskudun,to be idle,avare kalmak,"PZ, AŞ, FA, HO"
1,cebazgu,TVE,cobazgams,"to press, to step on something",basmak,"PZ, AŞ",cebazgu,TVE,cobazgams,"to press, to step on something",basmak,"PZ, AŞ"
2,cebgaru,TVE,cabgars,to lament over something,ağıt yakmak,PZ,cebgaru,TVE,cabgars,to lament over something,ağıt yakmak,PZ

================================================================================
_28
Shape: (0, 2)
Columns: ['region', 'region_code']

Empty DataFrame
Columns: [region, region_code]
Index: []

================================================================================
base
Shape: (695, 17)
Columns: ['Laz Infinitive', 'Category', 'Laz 3rd Person Singular Present', 'English Translation', 'Turkish Verb', 'Region', 'verb_family_id', 'preverb_family', 'infinitive', 'code', 'present_3sg', 'meaning_english', 'meaning_turkish', 'region', 'verb_category_id', 'region_code', 'dialect_id']

,Laz Infinitive,Category,Laz 3rd Person Singular Present,English Translation,Turkish Verb,Region,verb_family_id,preverb_family,infinitive,code,present_3sg,meaning_english,meaning_turkish,region,verb_category_id,region_code,dialect_id
0,avara doskudu,TVM,avara doskudun,to be idle,avare kalmak,"PZ, AŞ, FA, HO",19,<NA>,avara doskudu,TVM,avara doskudun,to be idle,avare kalmak,"PZ, AŞ, FA, HO",1,PZ,2
0,avara doskudu,TVM,avara doskudun,to be idle,avare kalmak,"PZ, AŞ, FA, HO",19,<NA>,avara doskudu,TVM,avara doskudun,to be idle,avare kalmak,"PZ, AŞ, FA, HO",1,AŞ,1
0,avara doskudu,TVM,avara doskudun,to be idle,avare kalmak,"PZ, AŞ, FA, HO",19,<NA>,avara doskudu,TVM,avara doskudun,to be idle,avare kalmak,"PZ, AŞ, FA, HO",1,FA,3

================================================================================
verbs_to_insert
Shape: (653, 10)
Columns: ['verb_family_id', 'verb_category_id', 'dialect_id', 'infinitive', 'present_3sg', 'meaning_english', 'meaning_turkish', 'requires_marker', 'has_optional_prefix_ko', 'has_optional_prefix_do']

,verb_family_id,verb_category_id,dialect_id,infinitive,present_3sg,meaning_english,meaning_turkish,requires_marker,has_optional_prefix_ko,has_optional_prefix_do
0,19,1,2,avara doskudu,avara doskudun,to be idle,avare kalmak,False,False,False
0,19,1,1,avara doskudu,avara doskudun,to be idle,avare kalmak,False,False,False
0,19,1,3,avara doskudu,avara doskudun,to be idle,avare kalmak,False,False,False

================================================================================
_29
Shape: (5, 8)
Columns: ['verb_family_id', 'verb_category_id', 'dialect_id', 'infinitive', 'present_3sg', 'meaning_english', 'meaning_turkish', 'requires_marker']

,verb_family_id,verb_category_id,dialect_id,infinitive,present_3sg,meaning_english,meaning_turkish,requires_marker
0,19,1,2,avara doskudu,avara doskudun,to be idle,avare kalmak,False
0,19,1,1,avara doskudu,avara doskudun,to be idle,avare kalmak,False
0,19,1,3,avara doskudu,avara doskudun,to be idle,avare kalmak,False

================================================================================
verb_family_seed
Shape: (205, 2)
Columns: ['verb_family_id', 'family_code']

     verb_family_id family_code
60                1        None
259               2        None
142               3        None

================================================================================
to_insert
Shape: (30, 3)
Columns: ['spelling', 'preverb_group', 'notes']

  spelling preverb_group notes
0      ama          None  None
1       ce          None  None
2     cela          None  None

================================================================================
_34
Shape: (1, 1)
Columns: ['n_verbs']

   n_verbs
0      653

================================================================================
_36
Shape: (1, 1)
Columns: ['n_verbs']

   n_verbs
0      653

================================================================================
_37
Shape: (20, 4)
Columns: ['dialect_id', 'infinitive', 'present_3sg', 'verb_category_id']

   dialect_id infinitive present_3sg  verb_category_id
0           1    cexvamu   cuxvamams                 2
1           2    cexvamu   cuxvamams                 2
2           3    gexvamu  gyuxvamams                 2

================================================================================
_38
Shape: (1, 1)
Columns: ['n_verbs']

   n_verbs
0      653

================================================================================
_39
Shape: (0, 3)
Columns: ['dialect_id', 'infinitive', 'n']

Empty DataFrame
Columns: [dialect_id, infinitive, n]
Index: []

================================================================================
_40
Shape: (25, 8)
Columns: ['verb_id', 'verb_family_id', 'dialect', 'category', 'infinitive', 'present_3sg', 'meaning_english', 'meaning_turkish']

,verb_id,verb_family_id,dialect,category,infinitive,present_3sg,meaning_english,meaning_turkish
0,653,210,Ardeşen,Ergative verb,cexvamu,cuxvamams,to celebrate,kutlamak
1,652,210,Pazar,Ergative verb,cexvamu,cuxvamams,to celebrate,kutlamak
2,651,210,Fındıklı/Arhavi,Ergative verb,gexvamu,gyuxvamams,to celebrate,kutlamak

================================================================================
preverb_df_db
Shape: (30, 3)
Columns: ['spelling', 'preverb_group', 'notes']

  spelling preverb_group notes
0      ama          None  None
1       ce          None  None
2     cela          None  None

================================================================================
_43
Shape: (30, 4)
Columns: ['preverb_id', 'spelling', 'preverb_group', 'notes']

   preverb_id spelling preverb_group notes
0           1      ama          None  None
1           2       ce          None  None
2           3     cela          None  None

================================================================================
_44
Shape: (30, 4)
Columns: ['preverb_id', 'spelling', 'preverb_group', 'notes']

   preverb_id spelling preverb_group notes
0           1      ama          None  None
1           2       ce          None  None
2           3     cela          None  None

In [47]:
# Pronoun table
import pandas as pd
from sqlalchemy import text

# --------------------------------------------------
# 1) Inspect the actual dialect rows in the database
# --------------------------------------------------
with engine.connect() as conn:
    df_dialects = pd.read_sql(
        text("SELECT dialect_id, english_name, turkish_name, laz_name FROM dialect ORDER BY dialect_id"),
        conn
    )

display(df_dialects)

# --------------------------------------------------
# 2) Dialect IDs from the actual database
# --------------------------------------------------
DIALECTS = {
    "AŞ": 1,  # Ardeşen
    "PZ": 2,  # Pazar
    "FA": 3,  # Fındıklı/Arhavi
    "HO": 4,  # Hopa
}

FRAMES = ["Nominative", "Dative", "Ergative"]

# --------------------------------------------------
# 3) Pronoun source of truth
# --------------------------------------------------
PRONOUNS = {
    "AŞ": {
        "S1SG": "ma",
        "S2SG": "si",
        "S3SG": {
            "Nominative": "him",
            "Dative": "him",
            "Ergative": "him",
        },
        "S1PL": "şǩu",
        "S2PL": "t̆ǩva",
        "S3PL": {
            "Nominative": "hini",
            "Dative": "hini",
            "Ergative": "hini",
        },
        "O1SG": "ma",
        "O2SG": "si",
        "O3SG": "him",
        "O1PL": "şǩu",
        "O2PL": "t̆ǩva",
        "O3PL": "hini",
    },

    "PZ": {
        "S1SG": "ma",
        "S2SG": "si",
        "S3SG": {
            "Nominative": "him",
            "Dative": "himus",
            "Ergative": "himuk",
        },
        "S1PL": "şǩu",
        "S2PL": "t̆ǩva",
        "S3PL": {
            "Nominative": "hini",
            "Dative": "hinis",
            "Ergative": "hinik",
        },
        "O1SG": "ma",
        "O2SG": "si",
        "O3SG": "him",
        "O1PL": "şǩu",
        "O2PL": "t̆ǩva",
        "O3PL": "hini",
    },

    "FA": {
        "S1SG": "ma",
        "S2SG": "si",
        "S3SG": {
            "Nominative": "heya",
            "Dative": "heyas",
            "Ergative": "heyak",
        },
        "S1PL": "çku",
        "S2PL": "tkva",
        "S3PL": {
            "Nominative": "hentepe",
            "Dative": "hentepes",
            "Ergative": "hentepek",
        },
        "O1SG": "ma",
        "O2SG": "si",
        "O3SG": "heya",
        "O1PL": "çku",
        "O2PL": "tkva",
        "O3PL": "hentepe",
    },

    "HO": {
        "S1SG": "ma",
        "S2SG": "si",
        "S3SG": {
            "Nominative": "(h)em",
            "Dative": "(h)emus",
            "Ergative": "(h)emuk",
        },
        "S1PL": "çkin",
        "S2PL": "tkvan",
        "S3PL": {
            "Nominative": "entepe",
            "Dative": "entepes",
            "Ergative": "entepek",
        },
        "O1SG": "ma",
        "O2SG": "si",
        "O3SG": "(h)em",
        "O1PL": "çkin",
        "O2PL": "tkvan",
        "O3PL": "entepe",
    },
}

# --------------------------------------------------
# 4) Expand to rows
# --------------------------------------------------
rows = []

for short_key, forms_by_code in PRONOUNS.items():
    dialect_id = DIALECTS[short_key]

    for code, form_value in forms_by_code.items():
        if isinstance(form_value, dict):
            for frame in FRAMES:
                rows.append({
                    "dialect_id": dialect_id,
                    "code": code,
                    "frame": frame,
                    "form": form_value[frame],
                })
        else:
            for frame in FRAMES:
                rows.append({
                    "dialect_id": dialect_id,
                    "code": code,
                    "frame": frame,
                    "form": form_value,
                })

df_pronoun = pd.DataFrame(rows)

display(df_pronoun.head(30))
display(df_pronoun.tail(30))

# --------------------------------------------------
# 5) Sanity checks
# --------------------------------------------------
expected_rows = 4 * 12 * 3
print("Row count:", len(df_pronoun), "expected:", expected_rows)

todo_rows = df_pronoun[df_pronoun["form"].astype(str).str.startswith("TODO_")]
display(todo_rows)

# --------------------------------------------------
# 6) Write to DB (uncomment when ready)
# --------------------------------------------------
df_pronoun.to_sql("pronoun", engine, if_exists="append", index=False)

   dialect_id     english_name     turkish_name     laz_name
0           1          Ardeşen          Ardeşen    Art̆aşeni
1           2            Pazar            Pazar        Atina
2           3  Fındıklı/Arhavi  Fındıklı/Arhavi  Viǯe/Arkabi
3           4             Hopa             Hopa         Xopa

    dialect_id  code       frame   form
0            1  S1SG  Nominative     ma
1            1  S1SG      Dative     ma
2            1  S1SG    Ergative     ma
3            1  S2SG  Nominative     si
4            1  S2SG      Dative     si
5            1  S2SG    Ergative     si
6            1  S3SG  Nominative    him
7            1  S3SG      Dative    him
8            1  S3SG    Ergative    him
9            1  S1PL  Nominative    şǩu
10           1  S1PL      Dative    şǩu
11           1  S1PL    Ergative    şǩu
12           1  S2PL  Nominative  t̆ǩva
13           1  S2PL      Dative  t̆ǩva
14           1  S2PL    Ergative  t̆ǩva
15           1  S3PL  Nominative   hini
16           1  S3PL      Dative   hini
17           1  S3PL    Ergative   hini
18           1  O1SG  Nominative     ma
19           1  O1SG      Dative     ma
20           1  O1SG    Ergative     ma
21           1  O2SG  Nominative     si
22           1  O2SG      Dative     si
23           1  O2SG    Ergative     si
24           1  O3SG  Nominative    him
25           1  O3SG      Dative    him
26           1  O3SG    Ergative    him
27           1  O1PL  Nominative    şǩu
28           1  O1PL      Dative    şǩu
29           1  O1PL    Ergative    şǩu

     dialect_id  code       frame     form
114           4  S3SG  Nominative    (h)em
115           4  S3SG      Dative  (h)emus
116           4  S3SG    Ergative  (h)emuk
117           4  S1PL  Nominative     çkin
118           4  S1PL      Dative     çkin
119           4  S1PL    Ergative     çkin
120           4  S2PL  Nominative    tkvan
121           4  S2PL      Dative    tkvan
122           4  S2PL    Ergative    tkvan
123           4  S3PL  Nominative   entepe
124           4  S3PL      Dative  entepes
125           4  S3PL    Ergative  entepek
126           4  O1SG  Nominative       ma
127           4  O1SG      Dative       ma
128           4  O1SG    Ergative       ma
129           4  O2SG  Nominative       si
130           4  O2SG      Dative       si
131           4  O2SG    Ergative       si
132           4  O3SG  Nominative    (h)em
133           4  O3SG      Dative    (h)em
134           4  O3SG    Ergative    (h)em
135           4  O1PL  Nominative     çkin
136           4  O1PL      Dative     çkin
137           4  O1PL    Ergative     çkin
138           4  O2PL  Nominative    tkvan
139           4  O2PL      Dative    tkvan
140           4  O2PL    Ergative    tkvan
141           4  O3PL  Nominative   entepe
142           4  O3PL      Dative   entepe
143           4  O3PL    Ergative   entepe

Row count: 144 expected: 144

Empty DataFrame
Columns: [dialect_id, code, frame, form]
Index: []

144

In [48]:
print("verbs rows:", len(verbs))
print("missing dialect_id rows:", verbs["dialect_id"].isna().sum())
display(bad.head(20))

verbs rows: 695
missing dialect_id rows: 0

Empty DataFrame
Columns: [region, region_code]
Index: []

In [49]:
print(type(verbs_to_insert))
print(verbs_to_insert.shape)
display(verbs_to_insert.head())

<class 'pandas.core.frame.DataFrame'>
(653, 10)

,verb_family_id,verb_category_id,dialect_id,infinitive,present_3sg,meaning_english,meaning_turkish,requires_marker,has_optional_prefix_ko,has_optional_prefix_do
0,19,1,2,avara doskudu,avara doskudun,to be idle,avare kalmak,False,False,False
0,19,1,1,avara doskudu,avara doskudun,to be idle,avare kalmak,False,False,False
0,19,1,3,avara doskudu,avara doskudun,to be idle,avare kalmak,False,False,False
0,19,1,4,avara doskudu,avara doskudun,to be idle,avare kalmak,False,False,False
1,139,2,2,cebazgu,cobazgams,"to press, to step on something",basmak,False,False,False

In [50]:
import os, sys, importlib
from pathlib import Path
import pandas as pd

# -----------------------------
# CONFIG
# -----------------------------
PROJECT_DIR = Path(r"C:\Users\Adam\Lazverbcon\laz_verb_conjugator")
BACKEND_DIR = PROJECT_DIR / "backend"
OUT_PATH    = PROJECT_DIR / "SQL Lazverbcon" / "verb_form_seed_stage.csv"

assert PROJECT_DIR.exists(), PROJECT_DIR
assert BACKEND_DIR.exists(), BACKEND_DIR

# Ensure package imports work
os.chdir(PROJECT_DIR)
if str(PROJECT_DIR) not in sys.path:
    sys.path.insert(0, str(PROJECT_DIR))

from backend.conjugation import conjugate_verb, check_verb_existence

# -----------------------------
# MARKERS
# Backend naming note:
# - simple_causative=True  -> DB is_causative=True
# - causative=True         -> DB is_double_causative=True
# - applicative+causative  -> DB is_applicative + is_double_causative
# -----------------------------
MARKER_SPECS_NON_TVE = [
    dict(
        marker_name="none",
        applicative=False,
        causative=False,
        simple_causative=False,
        is_applicative=False,
        is_causative=False,
        is_double_causative=False,
    ),
]

MARKER_SPECS_TVE = [
    dict(
        marker_name="none",
        applicative=False,
        causative=False,
        simple_causative=False,
        is_applicative=False,
        is_causative=False,
        is_double_causative=False,
    ),
    dict(
        marker_name="applicative",
        applicative=True,
        causative=False,
        simple_causative=False,
        is_applicative=True,
        is_causative=False,
        is_double_causative=False,
    ),
    dict(
        marker_name="simple_causative",
        applicative=False,
        causative=False,
        simple_causative=True,
        is_applicative=False,
        is_causative=True,
        is_double_causative=False,
    ),
    dict(
        marker_name="double_causative",
        applicative=False,
        causative=True,
        simple_causative=False,
        is_applicative=False,
        is_causative=False,
        is_double_causative=True,
    ),
    dict(
        marker_name="applicative_double_causative",
        applicative=True,
        causative=True,
        simple_causative=False,
        is_applicative=True,
        is_causative=False,
        is_double_causative=True,
    ),
]

# Load tense modules
tense_modules = {
    "ivd_present": importlib.import_module("backend.notebooks.ivd_present"),
    "ivd_past": importlib.import_module("backend.notebooks.ivd_past"),
    "ivd_pastpro": importlib.import_module("backend.notebooks.ivd_pastpro"),
    "ivd_future": importlib.import_module("backend.notebooks.ivd_future"),
    "tvm_tve_presentperf": importlib.import_module("backend.notebooks.tvm_tve_presentperf"),
    "tvm_tve_potential": importlib.import_module("backend.notebooks.tvm_tve_potential"),
    "tvm_tve_passive": importlib.import_module("backend.notebooks.tvm_tve_passive"),
    "tvm_tense": importlib.import_module("backend.notebooks.tvm_tense"),
    "tve_present": importlib.import_module("backend.notebooks.tve_present"),
    "tve_pastpro": importlib.import_module("backend.notebooks.tve_pastpro"),
    "tve_past": importlib.import_module("backend.notebooks.tve_past"),
    "tve_future": importlib.import_module("backend.notebooks.tve_future"),
}

PRONOUN_TO_SUBJECT = {
    "ma": "S1SG", "si": "S2SG",
    "him": "S3SG", "himus": "S3SG", "himuk": "S3SG",
    "heya": "S3SG", "heyas": "S3SG", "heyak": "S3SG",
    "(h)em": "S3SG", "(h)emus": "S3SG", "(h)emuk": "S3SG",
    "şǩu": "S1PL", "çku": "S1PL", "çkin": "S1PL",
    "t̆ǩva": "S2PL", "tkva": "S2PL", "tkvan": "S2PL",
    "hini": "S3PL", "hinis": "S3PL", "hinik": "S3PL",
    "hentepe": "S3PL", "hentepes": "S3PL", "hentepek": "S3PL",
    "entepe": "S3PL", "entepes": "S3PL", "entepek": "S3PL",
}
PRONOUN_TO_OBJECT = {
    "ma": "O1SG", "si": "O2SG",
    "him": "O3SG", "himus": "O3SG", "himuk": "O3SG",
    "heya": "O3SG", "heyas": "O3SG", "heyak": "O3SG",
    "(h)em": "O3SG", "(h)emus": "O3SG", "(h)emuk": "O3SG",
    "şǩu": "O1PL", "çku": "O1PL", "çkin": "O1PL",
    "t̆ǩva": "O2PL", "tkva": "O2PL", "tkvan": "O2PL",
    "hini": "O3PL", "hinis": "O3PL", "hinik": "O3PL",
    "hentepe": "O3PL", "hentepes": "O3PL", "hentepek": "O3PL",
    "entepe": "O3PL", "entepes": "O3PL", "entepek": "O3PL",
}

DB_TO_BACKEND_TENSE = {
    "present": "present",
    "past": "past",
    "future": "future",
    "present_perfect": "presentperf",
    "past_progressive": "pastpro",
}
DB_TENSES = ["present", "past", "future", "present_perfect", "past_progressive"]

# -----------------------------
# DERIVATION (DB) -> ASPECT (backend arg)
# -----------------------------
DERIVATIONS = ["none", "passive", "potential"]
DERIVATION_TO_ASPECT = {"none": None, "passive": "passive", "potential": "potential"}

# -----------------------------
# MOODS (must match enums.sql): indicative / imperative / optative
# Note: negative imperative is stored as mood='imperative' (enforced by enums),
# but generated by neg_imperative=True.
# -----------------------------
MOOD_SPECS = [
    ("indicative", dict(optative=False, imperative=False, neg_imperative=False)),
    ("optative", dict(optative=True,  imperative=False, neg_imperative=False)),
    ("imperative", dict(optative=False, imperative=True,  neg_imperative=False)),
    ("negative_imperative", dict(optative=False, imperative=False, neg_imperative=True)),
]

# -----------------------------
# SOURCE: notebook df
# -----------------------------
if "verbs_to_insert" not in globals():
    raise NameError("verbs_to_insert not found in notebook globals().")

df_src = verbs_to_insert.copy()
df_src["infinitive"] = df_src["infinitive"].astype(str).str.strip()
df_src = df_src[df_src["infinitive"] != ""]

print("verbs_to_insert rows:", len(df_src))
display(df_src.head())

if df_src.empty:
    raise ValueError("verbs_to_insert is empty. Re-run the earlier notebook cell that creates verbs_to_insert.")

infinitives = sorted(df_src["infinitive"].unique())
print("Unique infinitives:", len(infinitives), "example:", infinitives[:10])

# -----------------------------
# GENERATE
# -----------------------------
rows = []
n_errors = 0
n_obj_fallbacks = 0
n_deriv_skips = 0
n_mood_skips = 0
n_marker_skips = 0

for i, infinitive in enumerate(infinitives, 1):
    # Decide once per infinitive whether marker generation is allowed
    exists_in_ivd, exists_in_tve, exists_in_tvm, exists_in_tvm_tve = check_verb_existence(infinitive, tense_modules)
    marker_specs = MARKER_SPECS_TVE if exists_in_tve else MARKER_SPECS_NON_TVE

    for db_mood, mood_flags in MOOD_SPECS:
        # non-indicative moods are stored with tense='present'
        tense_list = DB_TENSES if db_mood == "indicative" else ["present"]

        for db_tense in tense_list:
            backend_tense = DB_TO_BACKEND_TENSE[db_tense]

            for derivation in DERIVATIONS:
                # present perfect: no derivation, no object
                if db_tense == "present_perfect" and derivation != "none":
                    continue

                # derivation only in indicative
                if db_mood != "indicative" and derivation != "none":
                    continue

                aspect = DERIVATION_TO_ASPECT[derivation]

                for marker in marker_specs:
                    has_marker = (
                        marker["applicative"]
                        or marker["causative"]
                        or marker["simple_causative"]
                    )

                    # markers and derivation should not mix
                    # because object => derivation must be none
                    if has_marker and derivation != "none":
                        n_marker_skips += 1
                        continue

                    # present perfect cannot have object, so no markers there
                    if has_marker and db_tense == "present_perfect":
                        n_marker_skips += 1
                        continue

                    # markers are only for TVE
                    if has_marker and not exists_in_tve:
                        n_marker_skips += 1
                        continue

                    # object strategy:
                    # - derivation or present perfect => object must be NULL
                    # - otherwise request all objects and let backend/module decide
                    if derivation != "none" or db_tense == "present_perfect":
                        preferred_obj = None
                    elif exists_in_ivd or exists_in_tve:
                        preferred_obj = "all"
                    elif exists_in_tvm or exists_in_tvm_tve:
                        preferred_obj = None
                    else:
                        preferred_obj = None

                    try:
                        out = conjugate_verb(
                            tense_modules=tense_modules,
                            infinitive=infinitive,
                            tense=backend_tense,
                            aspect=aspect,
                            obj=preferred_obj,
                            subject="all",
                            applicative=marker["applicative"],
                            causative=marker["causative"],
                            simple_causative=marker["simple_causative"],
                            **mood_flags,
                        )
                    except ValueError as e:
                        msg = str(e)

                        # if we asked for objects but this combination cannot take one,
                        # retry subject-only
                        if preferred_obj is not None and (
                            ("cannot take an object" in msg) or
                            ("nesne alamaz" in msg)
                        ):
                            n_obj_fallbacks += 1
                            out = conjugate_verb(
                                tense_modules=tense_modules,
                                infinitive=infinitive,
                                tense=backend_tense,
                                aspect=aspect,
                                obj=None,
                                subject="all",
                                applicative=marker["applicative"],
                                causative=marker["causative"],
                                simple_causative=marker["simple_causative"],
                                **mood_flags,
                            )
                        else:
                            if db_mood != "indicative":
                                n_mood_skips += 1
                                if n_mood_skips <= 10:
                                    print(
                                        "MOOD SKIP:",
                                        infinitive, db_tense, derivation, db_mood, marker["marker_name"], "|", msg
                                    )
                            else:
                                n_errors += 1
                                if n_errors <= 10:
                                    print(
                                        "VALUEERROR:",
                                        infinitive, db_tense, derivation, db_mood, marker["marker_name"], "|", msg
                                    )
                            continue

                    res = out.get("result", None)

                    if not isinstance(res, dict):
                        n_errors += 1
                        if n_errors <= 5:
                            print(
                                "NON-DICT result:",
                                infinitive, db_tense, derivation, db_mood, marker["marker_name"], type(res), res
                            )
                        continue

                    if "error" in res:
                        # expected skips are common for some marker/mood combos
                        reason = ((out.get("meta") or {}).get("selected") or {}).get("reason")
                        if reason in {
                            "marker_requires_obj",
                            "ivd_marker_forbidden",
                            "no_output",
                            "marker_required",
                        }:
                            n_marker_skips += 1
                            if n_marker_skips <= 15:
                                print(
                                    "MARKER SKIP:",
                                    infinitive, db_tense, derivation, db_mood, marker["marker_name"], "|",
                                    res["error"]
                                )
                        else:
                            n_errors += 1
                            if n_errors <= 10:
                                print(
                                    "ERROR:",
                                    infinitive, db_tense, derivation, db_mood, marker["marker_name"], res["error"]
                                )
                        continue

                    for dialect_code, frame_dict in res.items():
                        if not isinstance(frame_dict, dict):
                            continue

                        for frame, items in frame_dict.items():
                            if not isinstance(items, list):
                                continue

                            for it in items:
                                if not isinstance(it, dict):
                                    continue

                                subj = (it.get("subject") or "").strip()
                                obj  = (it.get("object") or it.get("obj") or "").strip()

                                rows.append({
                                    "dialect_code": dialect_code,
                                    "frame": frame,

                                    "subject": subj,
                                    "object": obj if obj else None,

                                    "subject_code": PRONOUN_TO_SUBJECT.get(subj, None) if subj else None,
                                    "object_code": PRONOUN_TO_OBJECT.get(obj, None) if obj else None,

                                    "spelling": (it.get("conjugation") or "").strip(),

                                    "infinitive": infinitive,
                                    "tense": db_tense,
                                    "derivation": derivation,
                                    "mood": db_mood,

                                    "is_applicative": marker["is_applicative"],
                                    "is_causative": marker["is_causative"],
                                    "is_double_causative": marker["is_double_causative"],

                                    "optional_prefix": None,
                                })

    if i % 25 == 0:
        print(
            f"Processed {i}/{len(infinitives)} | rows: {len(rows)} | errors: {n_errors} "
            f"| obj fallbacks: {n_obj_fallbacks} | mood skips: {n_mood_skips} | marker skips: {n_marker_skips}"
        )

df_out = pd.DataFrame(rows)

if df_out.empty:
    print("\nFINAL rows: 0")
    print("Object fallbacks:", n_obj_fallbacks)
    print("Mood skips:", n_mood_skips)
    print("Marker skips:", n_marker_skips)
    print("No rows generated.")
else:
    df_out = df_out.drop_duplicates()

    print("\nFINAL rows:", len(df_out))
    print("Object fallbacks:", n_obj_fallbacks)
    print("Mood skips:", n_mood_skips)
    print("Marker skips:", n_marker_skips)
    print("Non-empty object count:", (df_out["object"].fillna("").str.strip() != "").sum())

    print("Writing to:", OUT_PATH.resolve())
    df_out.to_csv(OUT_PATH, index=False)

    print("Exists?", OUT_PATH.exists())
    if OUT_PATH.exists():
        print("mtime:", pd.Timestamp(OUT_PATH.stat().st_mtime, unit="s"))
        print("File size (bytes):", OUT_PATH.stat().st_size)
        display(df_out.head(10))

verbs_to_insert rows: 653

,verb_family_id,verb_category_id,dialect_id,infinitive,present_3sg,meaning_english,meaning_turkish,requires_marker,has_optional_prefix_ko,has_optional_prefix_do
0,19,1,2,avara doskudu,avara doskudun,to be idle,avare kalmak,False,False,False
0,19,1,1,avara doskudu,avara doskudun,to be idle,avare kalmak,False,False,False
0,19,1,3,avara doskudu,avara doskudun,to be idle,avare kalmak,False,False,False
0,19,1,4,avara doskudu,avara doskudun,to be idle,avare kalmak,False,False,False
1,139,2,2,cebazgu,cobazgams,"to press, to step on something",basmak,False,False,False

Unique infinitives: 299 example: ['avara doskudu', 'cebazgu', 'cebgaru', 'cedginu', 'cegapu', 'ceginu', 'celabalu', 'cemp̌onu', 'cexunu', 'cexvamu']
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
root: skud
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bazg
root: bgar
root: bgar
root: bgar
root: bgar
root: bgar
root: bgar
root: bgar
root: bgar
root: bgar
root: bgar
root: bgar
root: bgar
root: bgar
root: bgar
root: bgar
root: bgar
root: bgar
root: bgar
root: bgar
root: bgar
root: bgar
root: bgar
root: bgar
root: bgar
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
root: cadginen
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
root: gap
root: gap
root: gap
root: gap
root: gap
root: gap
root: gap
root: gap
root: gap
root: gap
root: gap
root: gap
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
root: gap
root: gap
root: gap
root: gap
root: gap
root: gap
root: gap
root: gap
root: gap
root: gap
root: gap
root: gap
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
root: gap
root: gap
root: gap
root: gap
root: gap
root: gap
root: gap
root: gap
root: gap
root: gap
root: gap
root: gap
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
root: gap
root: gap
root: gap
root: gap
root: gap
root: gap
root: gap
root: gap
root: gap
root: gap
root: gap
root: gap
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: gin
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: labal
root: mp̌on
root: mp̌on
root: mp̌on
root: mp̌on
root: mp̌on
root: mp̌on
root: mp̌on
root: mp̌on
root: mp̌on
root: mp̌on
root: mp̌on
root: mp̌on
root: mp̌on
root: mp̌on
root: mp̌on
root: mp̌on
root: mp̌on
root: mp̌on
root: mp̌on
root: mp̌on
root: mp̌on
root: mp̌on
root: mp̌on
root: mp̌on
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
root: xun
root: xun
root: xun
root: xun
root: xun
root: xun
root: xun
root: xun
root: xun
root: xun
root: xun
root: xun
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
root: xun
root: xun
root: xun
root: xun
root: xun
root: xun
root: xun
root: xun
root: xun
root: xun
root: xun
root: xun
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
root: xun
root: xun
root: xun
root: xun
root: xun
root: xun
root: xun
root: xun
root: xun
root: xun
root: xun
root: xun
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
root: xun
root: xun
root: xun
root: xun
root: xun
root: xun
root: xun
root: xun
root: xun
root: xun
root: xun
root: xun
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
preverb: ce
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: xvam
root: yon
root: yon
root: yon
root: yon
root: yon
root: yon
root: yon
root: yon
root: yon
root: yon
root: yon
root: yon
root: yon
root: yon
root: yon
root: yon
root: yon
root: yon
root: yon
root: yon
root: yon
root: yon
root: yon
root: yon
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: çam
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: ç̌
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
root: dval
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
root: bad
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
root: bal
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
root: bazginap
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
root: dgit
root: dgit
root: dgit
root: dgit
root: dgit
root: dgit
root: dgit
root: dgit
root: dgit
root: dgit
root: dgit
root: dgit
root: dgit
root: dgit
root: dgit
root: dgit
root: dgit
root: dgit
root: dgit
root: dgit
root: dgit
root: dgit
root: dgit
root: dgit
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
root: dgit
root: dgit
root: dgit
root: dgit
root: dgit
root: dgit
root: dgit
root: dgit
root: dgit
root: dgit
root: dgit
root: dgit
root: dgit
root: dgit
root: dgit
root: dgit
root: dgit
root: dgit
root: dgit
root: dgit
root: dgit
root: dgit
root: dgit
root: dgit
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do
preverb: do

,dialect_code,frame,subject,object,subject_code,object_code,spelling,infinitive,tense,derivation,mood,is_applicative,is_causative,is_double_causative,optional_prefix
0,PZ,Nominative,ma,None,S1SG,None,avara dopskudur,avara doskudu,present,none,indicative,False,False,False,None
1,PZ,Nominative,si,None,S2SG,None,avara doskudur,avara doskudu,present,none,indicative,False,False,False,None
2,PZ,Nominative,him,None,S3SG,None,avara doskudun,avara doskudu,present,none,indicative,False,False,False,None
3,PZ,Nominative,şǩu,None,S1PL,None,avara dopskudurt,avara doskudu,present,none,indicative,False,False,False,None
4,PZ,Nominative,t̆ǩva,None,S2PL,None,avara doskudurt,avara doskudu,present,none,indicative,False,False,False,None
5,PZ,Nominative,hini,None,S3PL,None,avara doskudunan,avara doskudu,present,none,indicative,False,False,False,None
6,AŞ,Nominative,ma,None,S1SG,None,avara dopskudur,avara doskudu,present,none,indicative,False,False,False,None
7,AŞ,Nominative,si,None,S2SG,None,avara doskudur,avara doskudu,present,none,indicative,False,False,False,None
8,AŞ,Nominative,him,None,S3SG,None,avara doskudun,avara doskudu,present,none,indicative,False,False,False,None
9,AŞ,Nominative,şǩu,None,S1PL,None,avara dopskudurt,avara doskudu,present,none,indicative,False,False,False,None

In [51]:
verbs_to_insert[verbs_to_insert["infinitive"].astype(str).str.strip() == "oskidu"]

,verb_family_id,verb_category_id,dialect_id,infinitive,present_3sg,meaning_english,meaning_turkish,requires_marker,has_optional_prefix_ko,has_optional_prefix_do
236,116,1,3,oskidu,skidun,to live,yaşamak,False,False,False
236,116,1,4,oskidu,skidun,to live,yaşamak,False,False,False

In [52]:
df_out[
    (df_out["frame"] == "Nominative") &
    (df_out["derivation"] == "passive")
].head(20)

,dialect_code,frame,subject,object,subject_code,object_code,spelling,infinitive,tense,derivation,mood,is_applicative,is_causative,is_double_causative,optional_prefix
24,PZ,Nominative,ma,None,S1SG,None,avara doviskuder,avara doskudu,present,passive,indicative,False,False,False,None
25,PZ,Nominative,si,None,S2SG,None,avara diskuder,avara doskudu,present,passive,indicative,False,False,False,None
26,PZ,Nominative,him,None,S3SG,None,avara diskuden,avara doskudu,present,passive,indicative,False,False,False,None
27,PZ,Nominative,şǩu,None,S1PL,None,avara doviskudert,avara doskudu,present,passive,indicative,False,False,False,None
28,PZ,Nominative,t̆ǩva,None,S2PL,None,avara diskudert,avara doskudu,present,passive,indicative,False,False,False,None
29,PZ,Nominative,hini,None,S3PL,None,avara diskudenan,avara doskudu,present,passive,indicative,False,False,False,None
30,AŞ,Nominative,ma,None,S1SG,None,avara doviskuder,avara doskudu,present,passive,indicative,False,False,False,None
31,AŞ,Nominative,si,None,S2SG,None,avara diskuder,avara doskudu,present,passive,indicative,False,False,False,None
32,AŞ,Nominative,him,None,S3SG,None,avara diskuden,avara doskudu,present,passive,indicative,False,False,False,None
33,AŞ,Nominative,şǩu,None,S1PL,None,avara doviskudert,avara doskudu,present,passive,indicative,False,False,False,None
34,AŞ,Nominative,t̆ǩva,None,S2PL,None,avara diskudert,avara doskudu,present,passive,indicative,False,False,False,None
35,AŞ,Nominative,hini,None,S3PL,None,avara diskudenan,avara doskudu,present,passive,indicative,False,False,False,None
36,FA,Nominative,ma,None,S1SG,None,avara dobiskuder,avara doskudu,present,passive,indicative,False,False,False,None
37,FA,Nominative,si,None,S2SG,None,avara diskuder,avara doskudu,present,passive,indicative,False,False,False,None
38,FA,Nominative,heya,None,S3SG,None,avara diskuden,avara doskudu,present,passive,indicative,False,False,False,None
39,FA,Nominative,çku,None,S1PL,None,avara dobiskudert,avara doskudu,present,passive,indicative,False,False,False,None
40,FA,Nominative,tkva,None,S2PL,None,avara diskudert,avara doskudu,present,passive,indicative,False,False,False,None
41,FA,Nominative,hentepe,None,S3PL,None,avara diskudenan,avara doskudu,present,passive,indicative,False,False,False,None
42,HO,Nominative,ma,None,S1SG,None,avara doviskuder,avara doskudu,present,passive,indicative,False,False,False,None
43,HO,Nominative,si,None,S2SG,None,avara diskuder,avara doskudu,present,passive,indicative,False,False,False,None

In [53]:
print("Writing to:", OUT_PATH)
print("Exists?", OUT_PATH.exists())
print("Absolute path:", OUT_PATH.resolve())
print("Last modified:", pd.Timestamp(OUT_PATH.stat().st_mtime, unit="s"))
print("File size:", OUT_PATH.stat().st_size)

Writing to: C:\Users\Adam\Lazverbcon\laz_verb_conjugator\SQL Lazverbcon\verb_form_seed_stage.csv
Exists? True
Absolute path: C:\Users\Adam\Lazverbcon\laz_verb_conjugator\SQL Lazverbcon\verb_form_seed_stage.csv
Last modified: 2026-03-14 23:42:45.867094278
File size: 56876868

In [54]:
import pandas as pd
from pathlib import Path

# -----------------------------
# PATHS
# -----------------------------
STAGE_PATH = Path(r"C:\Users\Adam\Lazverbcon\laz_verb_conjugator\SQL Lazverbcon\verb_form_seed_stage.csv")
FINAL_PATH = Path(r"C:\Users\Adam\Lazverbcon\laz_verb_conjugator\SQL Lazverbcon\verb_form_seed_final.csv")

# -----------------------------
# LOAD STAGE CSV
# -----------------------------
df_stage = pd.read_csv(STAGE_PATH, low_memory=False)

# Normalize blanks
for col in df_stage.columns:
    if df_stage[col].dtype == "object":
        df_stage[col] = df_stage[col].astype(str).str.strip()

df_stage = df_stage.replace({"": pd.NA, "nan": pd.NA, "None": pd.NA})

print("Stage rows:", len(df_stage))
print("Stage columns:", list(df_stage.columns))

# -----------------------------
# MAP backend dialect_code -> dialect_id
# -----------------------------
# Use the same mapping logic you already used earlier in the notebook
dialect_map = pd.read_sql(
    "SELECT dialect_id, english_name FROM dialect ORDER BY dialect_id;",
    engine
)

region_to_english = {
    "AŞ": "Ardeşen",
    "PZ": "Pazar",
    "FA": "Fındıklı/Arhavi",
    "HO": "Hopa",
}

english_to_id = dict(zip(dialect_map["english_name"], dialect_map["dialect_id"]))
region_to_id = {k: english_to_id[v] for k, v in region_to_english.items()}

df_stage["dialect_id"] = df_stage["dialect_code"].map(region_to_id)

bad_dialects = df_stage[df_stage["dialect_id"].isna()][["dialect_code"]].drop_duplicates()
if not bad_dialects.empty:
    print("Unmapped dialect codes:")
    display(bad_dialects)

# -----------------------------
# PULL verb_id LOOKUP FROM DB
# -----------------------------
verb_lookup = pd.read_sql("""
SELECT verb_id, dialect_id, infinitive
FROM verb;
""", engine)

# normalize join keys
verb_lookup["infinitive"] = verb_lookup["infinitive"].astype(str).str.strip()
df_stage["infinitive"] = df_stage["infinitive"].astype(str).str.strip()

# join stage rows to verb rows
df_final = df_stage.merge(
    verb_lookup,
    on=["dialect_id", "infinitive"],
    how="left",
    validate="many_to_one"
)

missing_verbs = df_final[df_final["verb_id"].isna()][["dialect_code", "dialect_id", "infinitive"]].drop_duplicates()
print("Rows with missing verb_id:", len(missing_verbs))
if not missing_verbs.empty:
    display(missing_verbs.head(50))

# -----------------------------
# BUILD FINAL verb_form DATAFRAME
# schema.sql expects:
# verb_id, subject, object, tense, derivation, mood,
# is_applicative, is_causative, is_double_causative,
# optional_prefix, spelling
# -----------------------------
df_final["subject"] = df_final["subject_code"]
df_final["object"] = df_final["object_code"]

# optional cleanup: blanks -> NA
df_final["subject"] = df_final["subject"].replace({"": pd.NA})
df_final["object"]  = df_final["object"].replace({"": pd.NA})
df_final["optional_prefix"] = df_final["optional_prefix"].replace({"": pd.NA})

verb_form_seed = df_final[[
    "verb_id",
    "subject",
    "object",
    "tense",
    "derivation",
    "mood",
    "is_applicative",
    "is_causative",
    "is_double_causative",
    "optional_prefix",
    "spelling",
]].copy()

# -----------------------------
# TYPE CLEANUP
# -----------------------------
verb_form_seed = verb_form_seed.dropna(subset=["verb_id", "subject", "tense", "derivation", "mood", "spelling"])

verb_form_seed["verb_id"] = verb_form_seed["verb_id"].astype(int)
verb_form_seed["is_applicative"] = verb_form_seed["is_applicative"].astype(bool)
verb_form_seed["is_causative"] = verb_form_seed["is_causative"].astype(bool)
verb_form_seed["is_double_causative"] = verb_form_seed["is_double_causative"].astype(bool)

# de-dupe final rows
verb_form_seed = verb_form_seed.drop_duplicates().reset_index(drop=True)

print("Final DB-ready rows:", len(verb_form_seed))
display(verb_form_seed.head(20))

# -----------------------------
# OPTIONAL SANITY CHECKS
# -----------------------------
print("Null object rows:", verb_form_seed["object"].isna().sum())
print("Applicative rows without object:",
      ((verb_form_seed["is_applicative"]) & (verb_form_seed["object"].isna())).sum())
print("Causative rows without object:",
      (((verb_form_seed["is_causative"]) | (verb_form_seed["is_double_causative"])) & (verb_form_seed["object"].isna())).sum())

# -----------------------------
# WRITE FINAL CSV
# -----------------------------
verb_form_seed.to_csv(FINAL_PATH, index=False)
print("Wrote:", FINAL_PATH)
print("Exists?", FINAL_PATH.exists())

Stage rows: 568004
Stage columns: ['dialect_code', 'frame', 'subject', 'object', 'subject_code', 'object_code', 'spelling', 'infinitive', 'tense', 'derivation', 'mood', 'is_applicative', 'is_causative', 'is_double_causative', 'optional_prefix']
Rows with missing verb_id: 98

       dialect_code  dialect_id    infinitive
16758            HO           4  coxo gedvalu
20130            HO           4   dobazginapu
24426            FA           3       dodginu
25434            HO           4        dodumu
30804            HO           4        doguru
35364            HO           4         doinu
39660            HO           4     doloç̌aru
52402            PZ           2        doǯonu
52438            AŞ           1        doǯonu
52474            HO           4        doǯonu
53458            HO           4       elaşinu
71716            HO           4      gamaçamu
77366            HO           4       gebažgu
79690            HO           4        geginu
81838            HO           4      geloǩidu
86134            HO           4      gemp̌onu
88634            HO           4       gexvamu
90362            HO           4        geçamu
92510            HO           4        geç̌ǩu
101630           HO           4      gonç̌elu
106326           HO           4        goxiru
110730           HO           4        goşinu
116314           FA           3        lumcun
116320           HO           4        lumcun
116690           HO           4       mebazgu
118910           HO           4    memgvapinu
123314           FA           3      memgvapu
127678           HO           4       memçinu
129898           HO           4    mendoğmalu
140638           HO           4        meçamu
144934           HO           4       meşvelu
153526           HO           4        meşǩvu
162046           HO           4        meǩoru
169070           PZ           2   moğerdinams
174306           HO           4         obaxu
183250           PZ           2         obonu
183286           AŞ           1         obonu
183322           FA           3         obonu
188620           HO           4        ocginu
190768           HO           4         ocoxu
193106           HO           4          ognu
197402           HO           4         ogoru
205994           HO           4          ogzu
212438           HO           4         okadu
216734           HO           4         okosu
222032           PZ           2         olalu
222068           AŞ           1         olalu
222104           FA           3         olalu
226328           HO           4       olasiru
235332           HO           4       omeselu

Final DB-ready rows: 473059

,verb_id,subject,object,tense,derivation,mood,is_applicative,is_causative,is_double_causative,optional_prefix,spelling
0,1,S1SG,<NA>,present,none,indicative,False,False,False,NaN,avara dopskudur
1,1,S2SG,<NA>,present,none,indicative,False,False,False,NaN,avara doskudur
2,1,S3SG,<NA>,present,none,indicative,False,False,False,NaN,avara doskudun
3,1,S1PL,<NA>,present,none,indicative,False,False,False,NaN,avara dopskudurt
4,1,S2PL,<NA>,present,none,indicative,False,False,False,NaN,avara doskudurt
5,1,S3PL,<NA>,present,none,indicative,False,False,False,NaN,avara doskudunan
6,2,S1SG,<NA>,present,none,indicative,False,False,False,NaN,avara dopskudur
7,2,S2SG,<NA>,present,none,indicative,False,False,False,NaN,avara doskudur
8,2,S3SG,<NA>,present,none,indicative,False,False,False,NaN,avara doskudun
9,2,S1PL,<NA>,present,none,indicative,False,False,False,NaN,avara dopskudurt
10,2,S2PL,<NA>,present,none,indicative,False,False,False,NaN,avara doskudurt
11,2,S3PL,<NA>,present,none,indicative,False,False,False,NaN,avara doskudunan
12,3,S1SG,<NA>,present,none,indicative,False,False,False,NaN,avara dopskudur
13,3,S2SG,<NA>,present,none,indicative,False,False,False,NaN,avara doskudur
14,3,S3SG,<NA>,present,none,indicative,False,False,False,NaN,avara doskudun
15,3,S1PL,<NA>,present,none,indicative,False,False,False,NaN,avara dopskudurt
16,3,S2PL,<NA>,present,none,indicative,False,False,False,NaN,avara doskudurt
17,3,S3PL,<NA>,present,none,indicative,False,False,False,NaN,avara doskudunan
18,4,S1SG,<NA>,present,none,indicative,False,False,False,NaN,avara dopskudur
19,4,S2SG,<NA>,present,none,indicative,False,False,False,NaN,avara doskudur

Null object rows: 38013
Applicative rows without object: 0
Causative rows without object: 0
Wrote: C:\Users\Adam\Lazverbcon\laz_verb_conjugator\SQL Lazverbcon\verb_form_seed_final.csv
Exists? True

In [55]:
test_inf = "ot̆axu"  # TVE

for obj_setting in [None, "all"]:
    out = conjugate_verb(
        tense_modules=tense_modules,
        infinitive=test_inf,
        tense="past",
        aspect=None,
        obj=obj_setting,
        subject="all",
        optative=False,
        imperative=False,
        neg_imperative=False,
        applicative=False,
        causative=False,
        simple_causative=False,
    )

    print("\nobj =", obj_setting)
    print("meta exists_in_tve:", out.get("meta", {}).get("exists_in_tve"))
    print("meta selected:", out.get("meta", {}).get("selected"))
    print("result dialects:", list(out.get("result", {}).keys())[:4])

    # show what's inside each dialect (type + preview)
    for d in list(out.get("result", {}).keys())[:2]:
        val = out["result"][d]
        print(" ", d, "type:", type(val))
        if isinstance(val, dict):
            print("   frames:", list(val.keys()))
        else:
            print("   value preview:", str(val)[:200])

obj = None
meta exists_in_tve: True
meta selected: {'path': 'tense', 'ivd_mapping': {}, 'tve_mapping': {'present': ['tve_present'], 'past': ['tve_past'], 'future': ['tve_future'], 'pastpro': ['tve_pastpro']}, 'tvm_mapping': {}}
result dialects: ['FA', 'AŞ', 'PZ', 'HO']
  FA type: <class 'dict'>
   frames: ['Ergative']
  AŞ type: <class 'dict'>
   frames: ['Ergative']

obj = all
meta exists_in_tve: True
meta selected: {'path': 'tense', 'ivd_mapping': {}, 'tve_mapping': {'present': ['tve_present'], 'past': ['tve_past'], 'future': ['tve_future'], 'pastpro': ['tve_pastpro']}, 'tvm_mapping': {}}
result dialects: ['FA', 'AŞ', 'PZ', 'HO']
  FA type: <class 'dict'>
   frames: ['Ergative']
  AŞ type: <class 'dict'>
   frames: ['Ergative']

In [56]:
print("STAGE rows:", len(df_stage))
print("AFTER MERGE rows:", len(df_final))

print("\nMissing dialect_id:", df_stage["dialect_id"].isna().sum())
print("Missing verb_id:", df_final["verb_id"].isna().sum())
print("Missing subject_code:", df_final["subject_code"].isna().sum())
print("Missing tense:", df_final["tense"].isna().sum())
print("Missing derivation:", df_final["derivation"].isna().sum())
print("Missing mood:", df_final["mood"].isna().sum())
print("Missing spelling:", df_final["spelling"].isna().sum())

before_dropna = len(df_final)
tmp = df_final.copy()
tmp["subject"] = tmp["subject_code"]
tmp["object"] = tmp["object_code"]

after_dropna = len(tmp.dropna(subset=["verb_id", "subject", "tense", "derivation", "mood", "spelling"]))
print("\nLost at dropna:", before_dropna - after_dropna)

tmp2 = tmp.dropna(subset=["verb_id", "subject", "tense", "derivation", "mood", "spelling"]).copy()
before_dedup = len(tmp2)
after_dedup = len(tmp2.drop_duplicates())
print("Lost at drop_duplicates:", before_dedup - after_dedup)

bad_subjects = (
    df_final.loc[df_final["subject_code"].isna(), ["subject"]]
    .drop_duplicates()
    .sort_values("subject")
)
display(bad_subjects)
print("Unmapped subject strings:", len(bad_subjects))

bad_verbs = (
    df_final.loc[df_final["verb_id"].isna(), ["dialect_code", "dialect_id", "infinitive"]]
    .drop_duplicates()
    .sort_values(["dialect_code", "infinitive"])
)
display(bad_verbs.head(100))
print("Unique unmapped verb keys:", len(bad_verbs))

STAGE rows: 568004
AFTER MERGE rows: 568004

Missing dialect_id: 0
Missing verb_id: 94250
Missing subject_code: 163
Missing tense: 0
Missing derivation: 0
Missing mood: 0
Missing spelling: 0

Lost at dropna: 94395
Lost at drop_duplicates: 0

      subject
19134    <NA>

Unmapped subject strings: 1

       dialect_code  dialect_id   infinitive
52438            AŞ           1       doǯonu
183286           AŞ           1        obonu
222068           AŞ           1        olalu
472268           AŞ           1        ožiru
545290           AŞ           1          ren
...             ...         ...          ...
169070           PZ           2  moğerdinams
183250           PZ           2        obonu
222032           PZ           2        olalu
472232           PZ           2        ožiru
545296           PZ           2          ren

[98 rows x 3 columns]

Unique unmapped verb keys: 98

In [57]:
import pandas as pd
# -----------------------------
# 1) dialect mapping
# -----------------------------
region_to_dialect_id = {
    "AŞ": 1,
    "PZ": 2,
    "FA": 3,
    "HO": 4,
}

# -----------------------------
# 2) find missing verb keys directly from stage CSV
# -----------------------------
verb_lookup = pd.read_sql("""
    SELECT verb_id, dialect_id, infinitive
    FROM verb
""", engine)
verb_lookup["infinitive"] = verb_lookup["infinitive"].astype(str).str.strip()

df_stage["infinitive"] = df_stage["infinitive"].astype(str).str.strip()
df_stage["dialect_id"] = df_stage["dialect_code"].map(region_to_dialect_id)

missing_keys = (
    df_stage[["dialect_id", "dialect_code", "infinitive"]]
    .drop_duplicates()
    .merge(
        verb_lookup[["dialect_id", "infinitive"]],
        on=["dialect_id", "infinitive"],
        how="left",
        indicator=True
    )
)

missing_keys = (
    missing_keys[missing_keys["_merge"] == "left_only"]
    .drop(columns=["_merge"])
    .drop_duplicates()
    .sort_values(["dialect_id", "infinitive"])
    .reset_index(drop=True)
)

print("Missing verb keys:", len(missing_keys))
display(missing_keys.head(100))

# -----------------------------
# 3) use existing verbs_to_insert as metadata donor by infinitive
#    (same infinitive -> reuse family/category/meaning/etc.)
# -----------------------------
vti = verbs_to_insert.copy()
vti["infinitive"] = vti["infinitive"].astype(str).str.strip()

# pick one donor row per infinitive
donor_cols = [
    "infinitive",
    "verb_family_id",
    "verb_category_id",
    "present_3sg",
    "meaning_english",
    "meaning_turkish",
    "requires_marker",
]
donor_cols = [c for c in donor_cols if c in vti.columns]

donors = (
    vti[donor_cols]
    .drop_duplicates()
    .sort_values(["infinitive"])
    .drop_duplicates(subset=["infinitive"], keep="first")
)

missing_verbs = missing_keys.merge(
    donors,
    on="infinitive",
    how="left",
    validate="many_to_one"
)

print("Rows to insert into verb:", len(missing_verbs))
display(missing_verbs.head(50))

# sanity check
missing_metadata = missing_verbs[
    missing_verbs["verb_family_id"].isna() | missing_verbs["verb_category_id"].isna()
]
print("Rows missing donor metadata:", len(missing_metadata))
if len(missing_metadata):
    display(missing_metadata.head(50))

Missing verb keys: 98

    dialect_id dialect_code    infinitive
0            1           AŞ        doǯonu
1            1           AŞ         obonu
2            1           AŞ         olalu
3            1           AŞ         ožiru
4            1           AŞ           ren
..         ...          ...           ...
93           4           HO         oǩoru
94           4           HO        oǩoǯǩu
95           4           HO         oǯilu
96           4           HO         oʒadu
97           4           HO  çxomi oç̌opu

[98 rows x 3 columns]

Rows to insert into verb: 98

,dialect_id,dialect_code,infinitive,verb_family_id,verb_category_id,present_3sg,meaning_english,meaning_turkish,requires_marker
0,1,AŞ,doǯonu,188,3,daǯonen,to think,sanmak,False
1,1,AŞ,obonu,40,2,ibons,to clean (a body part),vucudun bir bolumunu veya tamamını yıkamak,False
2,1,AŞ,olalu,9,2,lalups,"to bark, to talk nonsene","havlamak, boş konuşmak",False
3,1,AŞ,ožiru,109,2,žirops,to see,görmek,False
4,1,AŞ,ren,203,1,ren,to be,olmak,False
5,2,PZ,doǯonu,188,3,daǯonen,to think,sanmak,False
6,2,PZ,moğerdinams,39,2,moğerdinams,"to cheat, to defraud",aldatmak,False
7,2,PZ,obonu,40,2,ibons,to clean (a body part),vucudun bir bolumunu veya tamamını yıkamak,False
8,2,PZ,olalu,9,2,lalups,"to bark, to talk nonsene","havlamak, boş konuşmak",False
9,2,PZ,ožiru,109,2,žirops,to see,görmek,False
10,2,PZ,ren,203,1,ren,to be,olmak,False
11,3,FA,dodginu,175,3,dvadginen,to stand,ayakta durmak,False
12,3,FA,lumcun,26,1,lumcun,to become evening,akşam olmak,False
13,3,FA,memgvapu,150,3,nampgvapen,to resemble,benzemek,False
14,3,FA,obonu,40,2,ibons,to clean (a body part),vucudun bir bolumunu veya tamamını yıkamak,False
15,3,FA,olalu,9,2,lalups,"to bark, to talk nonsene","havlamak, boş konuşmak",False
16,3,FA,op̌içvu,70,2,ip̌içvaps,to fast,oruç tutmak,False
17,3,FA,oskedinu,117,2,osǩedinams,"to raise, to keep someone alive","besleyerek yaşatmak, yaşamda tutmak",False
18,3,FA,oxenu,194,2,ikums,to do,yapmak,False
19,3,FA,oçinu,107,2,içinems,to know someone,tanımak,False
20,3,FA,oşinu,66,2,şinems,to respect,saygı göstermek,False
21,3,FA,ožiru,109,2,žirops,to see,görmek,False
22,3,FA,oǯilu,33,2,ǯilums,to pluck,koparmak,False
23,4,HO,coxo gedvalu,130,2,coxo gyodums,to name something/someone,adlandırmak,False
24,4,HO,dobazginapu,179,2,dobazginapams,to step on the floor,bastırmak,False
25,4,HO,dodumu,140,2,dodums,"to put, to place (something on the floor)",koymak (yere),False
26,4,HO,doguru,111,2,digurams,to learn,öğrenmek,False
27,4,HO,doinu,88,2,doinams,to give birth,doğurmak,False
28,4,HO,doloç̌aru,143,2,doloç̌arums,to record,kaydetmek,False
29,4,HO,doǯonu,188,3,daǯonen,to think,sanmak,False
30,4,HO,elaşinu,146,2,elişinams,to remember,anmak,False
31,4,HO,gamaçamu,159,2,gamaçams,to sell,satmak,False
32,4,HO,gebažgu,139,2,gyobazgams,"to press, to step on something",basmak,False
33,4,HO,geginu,84,2,gyoginams,to get someone become familiar with something,alıştırmak,False
34,4,HO,geloǩidu,94,2,geloǩidams,to hang,asmak,False
35,4,HO,gemp̌onu,195,2,gyomp̌onams,to vaccinate/fertilize,aşılamak,False
36,4,HO,gexvamu,210,2,gyuxvamams,to celebrate,kutlamak,False
37,4,HO,geçamu,98,2,geçams,to hit something/someone,vurmak (bir şeye),False
38,4,HO,geç̌ǩu,28,2,gyoç̌ǩams,to begin,başlamak,False
39,4,HO,gonç̌elu,126,3,ganç̌elen,to miss someone,özlemek,False
40,4,HO,goxiru,177,2,goixirams,to steal,araklamak,False
41,4,HO,goşinu,146,3,gaşinen,to remember,hatırlamak,False
42,4,HO,lumcun,26,1,lumcun,to become evening,akşam olmak,False
43,4,HO,mebazgu,136,2,nobazgams,to poop,sıçmak,False
44,4,HO,memgvapinu,114,2,numgvapinams,to liken,benzetmek,False
45,4,HO,memçinu,54,2,numçinams,"to declare, to inform",bildirmek,False
46,4,HO,mendoğmalu,185,2,menduğams,to take something by force,almak (zorla),False
47,4,HO,meçamu,87,2,meçams,to give,vermek,False
48,4,HO,meşvelu,97,2,nuşvelams,to help,yardım etmek,False
49,4,HO,meşǩvu,112,2,naşǩums,to liberate,azad etmek,False

Rows missing donor metadata: 0

In [58]:
from sqlalchemy import text

# keep only columns that are actually in your seed structure
insert_cols = [
    "verb_family_id",
    "verb_category_id",
    "dialect_id",
    "infinitive",
    "present_3sg",
    "meaning_english",
    "meaning_turkish",
    "requires_marker",
]
insert_cols = [c for c in insert_cols if c in missing_verbs.columns]

to_insert = missing_verbs[insert_cols].drop_duplicates().copy()

print("Prepared rows for DB insert:", len(to_insert))
display(to_insert.head(20))

records = to_insert.to_dict(orient="records")

if len(records) == 0:
    print("No missing verbs to insert.")
else:
    sql = text("""
    INSERT INTO verb (
        verb_family_id,
        verb_category_id,
        dialect_id,
        infinitive,
        present_3sg,
        meaning_english,
        meaning_turkish,
        requires_marker
    )
    VALUES (
        :verb_family_id,
        :verb_category_id,
        :dialect_id,
        :infinitive,
        :present_3sg,
        :meaning_english,
        :meaning_turkish,
        :requires_marker
    )
    ON CONFLICT (dialect_id, infinitive) DO NOTHING;
    """)

    with engine.begin() as conn:
        conn.execute(sql, records)

    print("Inserted missing verb rows (or skipped existing ones).")

Prepared rows for DB insert: 98

,verb_family_id,verb_category_id,dialect_id,infinitive,present_3sg,meaning_english,meaning_turkish,requires_marker
0,188,3,1,doǯonu,daǯonen,to think,sanmak,False
1,40,2,1,obonu,ibons,to clean (a body part),vucudun bir bolumunu veya tamamını yıkamak,False
2,9,2,1,olalu,lalups,"to bark, to talk nonsene","havlamak, boş konuşmak",False
3,109,2,1,ožiru,žirops,to see,görmek,False
4,203,1,1,ren,ren,to be,olmak,False
5,188,3,2,doǯonu,daǯonen,to think,sanmak,False
6,39,2,2,moğerdinams,moğerdinams,"to cheat, to defraud",aldatmak,False
7,40,2,2,obonu,ibons,to clean (a body part),vucudun bir bolumunu veya tamamını yıkamak,False
8,9,2,2,olalu,lalups,"to bark, to talk nonsene","havlamak, boş konuşmak",False
9,109,2,2,ožiru,žirops,to see,görmek,False
10,203,1,2,ren,ren,to be,olmak,False
11,175,3,3,dodginu,dvadginen,to stand,ayakta durmak,False
12,26,1,3,lumcun,lumcun,to become evening,akşam olmak,False
13,150,3,3,memgvapu,nampgvapen,to resemble,benzemek,False
14,40,2,3,obonu,ibons,to clean (a body part),vucudun bir bolumunu veya tamamını yıkamak,False
15,9,2,3,olalu,lalups,"to bark, to talk nonsene","havlamak, boş konuşmak",False
16,70,2,3,op̌içvu,ip̌içvaps,to fast,oruç tutmak,False
17,117,2,3,oskedinu,osǩedinams,"to raise, to keep someone alive","besleyerek yaşatmak, yaşamda tutmak",False
18,194,2,3,oxenu,ikums,to do,yapmak,False
19,107,2,3,oçinu,içinems,to know someone,tanımak,False

Inserted missing verb rows (or skipped existing ones).

In [59]:
import pandas as pd

# -----------------------------
# 1) rebuild the missing key list
# -----------------------------
missing_keys = (
    df_stage.merge(
        pd.read_sql("SELECT verb_id, dialect_id, infinitive FROM verb;", engine)
          .assign(infinitive=lambda d: d["infinitive"].astype(str).str.strip()),
        on=["dialect_id", "infinitive"],
        how="left"
    )
    .loc[lambda d: d["verb_id"].isna(), ["dialect_id", "infinitive"]]
    .drop_duplicates()
    .sort_values(["dialect_id", "infinitive"])
    .reset_index(drop=True)
)

print("Missing (dialect_id, infinitive) keys:", len(missing_keys))
display(missing_keys.head(100))

# -----------------------------
# 2) inspect whether they exist in verbs_to_insert
# -----------------------------
vti = verbs_to_insert.copy()
vti["infinitive"] = vti["infinitive"].astype(str).str.strip()

print("\nverbs_to_insert columns:")
print(list(vti.columns))

# choose available columns safely
candidate_cols = [c for c in ["dialect_id", "dialect_code", "infinitive", "category", "verb_category_id"] if c in vti.columns]
vti_small = vti[candidate_cols].drop_duplicates()

check = missing_keys.merge(
    vti_small,
    on=["dialect_id", "infinitive"],
    how="left",
    indicator=True
)

print("\nDo missing keys exist in verbs_to_insert?")
print(check["_merge"].value_counts(dropna=False))
display(check.head(100))

Missing (dialect_id, infinitive) keys: 0

Empty DataFrame
Columns: [dialect_id, infinitive]
Index: []

verbs_to_insert columns:
['verb_family_id', 'verb_category_id', 'dialect_id', 'infinitive', 'present_3sg', 'meaning_english', 'meaning_turkish', 'requires_marker', 'has_optional_prefix_ko', 'has_optional_prefix_do']

Do missing keys exist in verbs_to_insert?
_merge
left_only     0
right_only    0
both          0
Name: count, dtype: int64

Empty DataFrame
Columns: [dialect_id, infinitive, verb_category_id, _merge]
Index: []

In [60]:
# rebuild final dataframe after repair
df_final = df_stage.merge(
    pd.read_sql("SELECT verb_id, dialect_id, infinitive FROM verb", engine),
    on=["dialect_id", "infinitive"],
    how="left"
)

df_final["subject"] = df_final["subject_code"]
df_final["object"] = df_final["object_code"]

verb_form_seed = df_final[[
    "verb_id",
    "frame",
    "subject",
    "object",
    "tense",
    "derivation",
    "mood",
    "is_applicative",
    "is_causative",
    "is_double_causative",
    "optional_prefix",
    "spelling"
]].copy()

verb_form_seed = verb_form_seed.dropna(
    subset=["verb_id","subject","tense","derivation","mood","spelling"]
)

verb_form_seed = verb_form_seed.drop_duplicates()

print("FINAL rows:", len(verb_form_seed))


verb_form_seed.to_csv(FINAL_PATH, index=False)

FINAL rows: 567841

In [61]:
print("df_stage columns:")
print(df_stage.columns.tolist())

print("\nverb_form_seed columns:")
print(verb_form_seed.columns.tolist())

df_stage columns:
['dialect_code', 'frame', 'subject', 'object', 'subject_code', 'object_code', 'spelling', 'infinitive', 'tense', 'derivation', 'mood', 'is_applicative', 'is_causative', 'is_double_causative', 'optional_prefix', 'dialect_id']

verb_form_seed columns:
['verb_id', 'frame', 'subject', 'object', 'tense', 'derivation', 'mood', 'is_applicative', 'is_causative', 'is_double_causative', 'optional_prefix', 'spelling']

In [62]:
import pandas as pd
from sqlalchemy import text

verb_lookup = pd.read_sql(
    text("""
        SELECT verb_id, infinitive, dialect_id
        FROM verb
    """),
    engine
)

In [63]:
verb_lookup = pd.read_sql(
    text("""
        SELECT verb_id, infinitive, dialect_id
        FROM verb
    """),
    engine
)

dialect_map = {
    1: "AŞ",
    2: "PZ",
    3: "FA",
    4: "HO",
}

verb_form_seed_cmp = verb_form_seed.merge(
    verb_lookup,
    how="left",
    on="verb_id"
)

verb_form_seed_cmp["dialect_code"] = verb_form_seed_cmp["dialect_id"].map(dialect_map)
verb_form_seed_cmp["subject_code"] = verb_form_seed_cmp["subject"]
verb_form_seed_cmp["object_code"] = verb_form_seed_cmp["object"]

compare_cols = [
    "dialect_code",
    "infinitive",
    "frame",
    "subject_code",
    "object_code",
    "spelling",
    "tense",
    "derivation",
    "mood",
    "is_applicative",
    "is_causative",
    "is_double_causative",
    "optional_prefix",
]

for df in [df_stage, verb_form_seed_cmp]:
    df["dialect_code"] = df["dialect_code"].fillna("").astype(str).str.strip()
    df["subject_code"] = df["subject_code"].fillna("").astype(str).str.strip()
    df["object_code"] = df["object_code"].fillna("").astype(str).str.strip()
    df["optional_prefix"] = df["optional_prefix"].fillna("").astype(str).str.strip()
    df["spelling"] = df["spelling"].fillna("").astype(str).str.strip()
    df["infinitive"] = df["infinitive"].fillna("").astype(str).str.strip()
    df["frame"] = df["frame"].fillna("").astype(str).str.strip()
    df["tense"] = df["tense"].fillna("").astype(str).str.strip()
    df["derivation"] = df["derivation"].fillna("").astype(str).str.strip()
    df["mood"] = df["mood"].fillna("").astype(str).str.strip()

left = df_stage[compare_cols].drop_duplicates().copy()
right = verb_form_seed_cmp[compare_cols].drop_duplicates().copy()

dropped = left.merge(
    right,
    how="left",
    on=compare_cols,
    indicator=True
)

dropped = dropped[dropped["_merge"] == "left_only"]

print("Dropped rows:", len(dropped))
display(dropped.head(20))

Dropped rows: 163

,dialect_code,infinitive,frame,subject_code,object_code,spelling,tense,derivation,mood,is_applicative,is_causative,is_double_causative,optional_prefix,_merge
19134,HO,diç̌irs,Dative,,O1SG,dovaç̌irt̆i,past_progressive,none,indicative,False,False,False,,left_only
19135,HO,diç̌irs,Dative,,O2SG,diç̌irt̆i,past_progressive,none,indicative,False,False,False,,left_only
19136,HO,diç̌irs,Dative,,,diç̌irt̆u,past_progressive,none,indicative,False,False,False,,left_only
19137,HO,diç̌irs,Dative,,O1PL,dovaç̌irt̆it,past_progressive,none,indicative,False,False,False,,left_only
19138,HO,diç̌irs,Dative,,O2PL,diç̌irt̆it,past_progressive,none,indicative,False,False,False,,left_only
19139,HO,diç̌irs,Dative,,O3PL,diç̌irt̆u,past_progressive,none,indicative,False,False,False,,left_only
24834,HO,dodginu,Dative,,O1SG,dovadginert̆i,past_progressive,none,indicative,False,False,False,,left_only
24835,HO,dodginu,Dative,,O2SG,dvadginert̆i,past_progressive,none,indicative,False,False,False,,left_only
24836,HO,dodginu,Dative,,,dvadginert̆u,past_progressive,none,indicative,False,False,False,,left_only
24837,HO,dodginu,Dative,,O1PL,dovadginert̆it,past_progressive,none,indicative,False,False,False,,left_only
24838,HO,dodginu,Dative,,O2PL,dvadginert̆it,past_progressive,none,indicative,False,False,False,,left_only
24839,HO,dodginu,Dative,,O3PL,dvadginet̆u,past_progressive,none,indicative,False,False,False,,left_only
52918,HO,doǯonu,Dative,,O1SG,dovaǯonert̆i,past_progressive,none,indicative,False,False,False,,left_only
52919,HO,doǯonu,Dative,,O2SG,dvaǯonert̆i,past_progressive,none,indicative,False,False,False,,left_only
52920,HO,doǯonu,Dative,,,dvaǯonert̆u,past_progressive,none,indicative,False,False,False,,left_only
52921,HO,doǯonu,Dative,,O1PL,dovaǯonert̆it,past_progressive,none,indicative,False,False,False,,left_only
52922,HO,doǯonu,Dative,,O2PL,dvaǯonert̆it,past_progressive,none,indicative,False,False,False,,left_only
52923,HO,doǯonu,Dative,,O3PL,dvaǯonet̆u,past_progressive,none,indicative,False,False,False,,left_only
101858,HO,gonç̌elu,Dative,,O1SG,govanç̌elert̆i,past_progressive,none,indicative,False,False,False,,left_only
101859,HO,gonç̌elu,Dative,,O2SG,gvanç̌elert̆i,past_progressive,none,indicative,False,False,False,,left_only

In [64]:
import pandas as pd

# path to your CSV
csv_path = r"C:\Users\Adam\Lazverbcon\laz_verb_conjugator\SQL Lazverbcon\verb_form_seed_final.csv"

# load the CSV
df = pd.read_csv(csv_path)

print("Rows in CSV:", len(df))

# insert into postgres
df.to_sql(
    "verb_form",
    engine,
    if_exists="append",
    index=False,
    method="multi",
    chunksize=5000
)

print("Import finished.")

Rows in CSV: 567841
Import finished.

In [65]:
from sqlalchemy import text

with engine.connect() as conn:
    result = conn.execute(text("SELECT current_database();"))
    print(result.fetchall())

[('laz_test',)]

In [66]:
df.head()

,verb_id,frame,subject,object,tense,derivation,mood,is_applicative,is_causative,is_double_causative,optional_prefix,spelling
0,1,Nominative,S1SG,NaN,present,none,indicative,False,False,False,NaN,avara dopskudur
1,1,Nominative,S2SG,NaN,present,none,indicative,False,False,False,NaN,avara doskudur
2,1,Nominative,S3SG,NaN,present,none,indicative,False,False,False,NaN,avara doskudun
3,1,Nominative,S1PL,NaN,present,none,indicative,False,False,False,NaN,avara dopskudurt
4,1,Nominative,S2PL,NaN,present,none,indicative,False,False,False,NaN,avara doskudurt

In [67]:
df["tense"].unique()

array(['present', 'past', 'future', 'present_perfect', 'past_progressive'],
      dtype=object)

In [68]:
df["mood"].unique()

array(['indicative', 'optative', 'imperative', 'negative_imperative'],
      dtype=object)

In [69]:
df["subject"].unique()

array(['S1SG', 'S2SG', 'S3SG', 'S1PL', 'S2PL', 'S3PL'], dtype=object)

In [70]:
from sqlalchemy import inspect
inspect(engine).get_table_names()

['dialect',
 'pronoun',
 'verb_family',
 'verb',
 'root_infinitive',
 'verb_category',
 'verb_preverb',
 'preverb',
 'verb_form']

In [71]:
conjugate_verb(
    tense_modules=tense_modules,
    infinitive="oxtimu",
    tense="present",
    aspect="potential",
    obj=None,
    subject="all",
    applicative=False,
    causative=False,
    simple_causative=False,
    optative=False,
    imperative=False,
    neg_imperative=False
)

root: l
root: l
root: l
root: l
root: l
root: l
root: l
root: l
root: l
root: l
root: l
root: l

{'result': {'FA': {'Dative': [{'subject': 'ma',
     'object': '',
     'conjugation': 'malen'},
    {'subject': 'si', 'object': '', 'conjugation': 'galen'},
    {'subject': 'heyas', 'object': '', 'conjugation': 'alen'},
    {'subject': 'çku', 'object': '', 'conjugation': 'malenan'},
    {'subject': 'tkva', 'object': '', 'conjugation': 'galenan'},
    {'subject': 'hentepes', 'object': '', 'conjugation': 'alenan'}]},
  'HO': {'Dative': [{'subject': 'ma', 'object': '', 'conjugation': 'malen'},
    {'subject': 'si', 'object': '', 'conjugation': 'galen'},
    {'subject': '(h)emus', 'object': '', 'conjugation': 'alen'},
    {'subject': 'çkin', 'object': '', 'conjugation': 'malenan'},
    {'subject': 'tkvan', 'object': '', 'conjugation': 'galenan'},
    {'subject': 'entepes', 'object': '', 'conjugation': 'alenan'}]}},
 'meta': {'infinitive': 'oxtimu',
  'tense': 'present',
  'aspect': 'potential',
  'obj': None,
  'subject': 'all',
  'optative': False,
  'imperative': False,
  'neg_imperative': False,
  'applicative': False,
  'causative': False,
  'simple_causative': False,
  'has_markers': False,
  'exists_in_ivd': False,
  'exists_in_tve': False,
  'exists_in_tvm': True,
  'exists_in_tvm_tve': True,
  'selected': {'path': 'aspect', 'aspect_module': ['tvm_tve_potential']}}}